<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Tests\Controllers;

use ApiB4CLib\Controllers\DescontosController;
use ApiB4CLib\Exceptions;
use ApiB4CLib\Models;
use Core\TestCase\TestParam;

class DescontosControllerTest extends BaseTestController
{
    /**
     * @var DescontosController DescontosController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getDescontosController();
    }

    public function testCadastrarDesconto()
    {
        // Perform API call
        try {
            self::$controller->cadastrarDesconto();
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase(null)->expectStatus(200)->assert();
    }

    public function testCadastrarDesconto1()
    {
        // Parameters for the API call
        $body = TestParam::object(
            "{\r\n  \"cpf_cnpj\": \"08113640975\",\r\n  \"titulo\": \"GOLD\",\r\n  \"tipo_desco" .
            "nto\": 1,\r\n  \"desconto\": 17,\r\n  \"inicio\": \"2024-08-07 12:15:10\",\r\n  \"f" .
            "im\": \"2024-09-06 12:15:10\"\r\n}",
            Models\CadastrarDescontoRequest::class
        );

        // Perform API call
        try {
            self::$controller->cadastrarDesconto1($body);
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase(null)->expectStatus(200)->assert();
    }

    public function testAtualizarDesconto()
    {
        // Parameters for the API call
        $body = TestParam::object(
            "{\r\n  \"titulo\": \"PLATINA\",\r\n  \"tipo_desconto\": 1,\r\n  \"desconto\": 12," .
            "\r\n  \"inicio\": \"2024-08-07 12:15:10\",\r\n  \"fim\": \"2024-09-06 12:15:10\"\r" .
            "\n}",
            Models\AtualizarDescontoRequest::class
        );

        // Perform API call
        try {
            self::$controller->atualizarDesconto($body);
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase(null)->expectStatus(200)->assert();
    }

    public function testDeletarDesconto()
    {
        // Perform API call
        try {
            self::$controller->deletarDesconto();
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase(null)->expectStatus(200)->assert();
    }
}
