<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Tests\Controllers;

use ApiB4CLib\Controllers\EntregasDoPedidoController;
use ApiB4CLib\Exceptions;
use ApiB4CLib\Models;
use Core\TestCase\TestParam;

class EntregasDoPedidoControllerTest extends BaseTestController
{
    /**
     * @var EntregasDoPedidoController EntregasDoPedidoController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getEntregasDoPedidoController();
    }

    public function testAtualizaEntrega()
    {
        // Parameters for the API call
        $body = TestParam::object(
            "{\r\n  \"rastreio\": \"AA123456789BR\",\r\n  \"data_envio\": \"2020-01-01 10:27:03" .
            "0\",\r\n  \"data_entrega\": \"2020-01-01 10:27:030\",\r\n  \"data\": \"2020-01-01 1" .
            "0:27:030\",\r\n  \"operacao\": \"002\",\r\n  \"numero\": \"15659\",\r\n  \"nf\": \"" .
            "NFe41200300915086000263550020003034231367245476\",\r\n  \"url_download\": \"https:/" .
            "/downloadnota.com.br/id=123\"\r\n}",
            Models\AtualizaEntregaRequest::class
        );

        // Perform API call
        try {
            self::$controller->atualizaEntrega($body);
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase(null)->expectStatus(200)->assert();
    }

    public function testListarEntregasDoPedido()
    {
        // Perform API call
        try {
            self::$controller->listarEntregasDoPedido();
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase(null)->expectStatus(200)->assert();
    }
}
