<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Tests\Controllers;

use ApiB4CLib\Controllers\EventosDaEntregaController;
use ApiB4CLib\Exceptions;
use ApiB4CLib\Models;
use Core\TestCase\TestParam;

class EventosDaEntregaControllerTest extends BaseTestController
{
    /**
     * @var EventosDaEntregaController EventosDaEntregaController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getEventosDaEntregaController();
    }

    public function testEnviaEventosDaEntrega()
    {
        // Parameters for the API call
        $body = TestParam::object(
            "{\r\n  \"status\": \"entregue\",\r\n  \"data\": \"2022-08-24 23:52:23\"\r\n}",
            Models\EnviaEventosDaEntregaRequest::class
        );

        // Perform API call
        try {
            self::$controller->enviaEventosDaEntrega($body);
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase(null)->expectStatus(200)->assert();
    }
}
