<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Tests\Controllers;

use ApiB4CLib\Controllers\PreOsController;
use ApiB4CLib\Exceptions;
use ApiB4CLib\Models;
use Core\TestCase\BodyMatchers\KeysBodyMatcher;
use Core\TestCase\TestParam;

class PreOsControllerTest extends BaseTestController
{
    /**
     * @var PreOsController PreOsController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getPreOsController();
    }

    public function testCadastraPreco()
    {
        // Parameters for the API call
        $body = TestParam::object(
            "{\r\n  \"id_campanha_promocional\": 2003,\r\n  \"preco\": 220\r\n}",
            Models\CadastraPrecoRequest::class
        );

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->cadastraPreco($body);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json;charset=utf-8', false];
        $headers['Date'] = ['Wed, 02 Sep 2020 20:14:04 GMT', false];
        $headers['Server'] = ['Apache', false];
        $headers['X-Powered-By'] = ['PHP/5.6.40', false];
        $headers['Expires'] = ['Thu, 19 Nov 1981 08:52:00 GMT', false];
        $headers['Cache-Control'] = ['no-store, no-cache, must-revalidate, post-check=0, pre-check=0', false];
        $headers['Pragma'] = ['no-cache', false];
        $headers['Vary'] = ['Authorization', false];
        $headers['Keep-Alive'] = ['timeout=5, max=100', false];
        $headers['Connection'] = ['Keep-Alive', false];
        $headers['Transfer-Encoding'] = ['chunked', false];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                "{\r\n  \"message\": \"Campanha cadastrada com sucesso\",\r\n  \"responseCode\": \"200\"\r\n}"
            )))
            ->assert();
    }

    public function testDeletarPreco()
    {
        // Parameters for the API call
        $body = TestParam::object(
            "{\r\n  \"id_campanha_promocional\": 2001\r\n}",
            Models\DeletarPrecoRequest::class
        );

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->deletarPreco($body);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json;charset=utf-8', false];
        $headers['Date'] = ['Wed, 02 Sep 2020 20:14:04 GMT', false];
        $headers['Server'] = ['Apache', false];
        $headers['X-Powered-By'] = ['PHP/5.6.40', false];
        $headers['Expires'] = ['Thu, 19 Nov 1981 08:52:00 GMT', false];
        $headers['Cache-Control'] = ['no-store, no-cache, must-revalidate, post-check=0, pre-check=0', false];
        $headers['Pragma'] = ['no-cache', false];
        $headers['Vary'] = ['Authorization', false];
        $headers['Keep-Alive'] = ['timeout=5, max=100', false];
        $headers['Connection'] = ['Keep-Alive', false];
        $headers['Transfer-Encoding'] = ['chunked', false];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                "{\r\n  \"message\": \"Campanha cadastrada com sucesso\",\r\n  \"responseCode\": \"200\"\r\n}"
            )))
            ->assert();
    }
}
