<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Tests;

use ApiB4CLib\ApiB4CClient;
use ApiB4CLib\ApiB4CClientBuilder;
use ApiB4CLib\Authentication\BasicAuthCredentialsBuilder;
use Core\Types\CallbackCatcher;

class ClientFactory
{
    public static function create(CallbackCatcher $httpCallback): ApiB4CClient
    {
        $clientBuilder = ApiB4CClientBuilder::init();
        $clientBuilder = self::addConfigurationFromEnvironment($clientBuilder);
        $clientBuilder = self::addTestConfiguration($clientBuilder);
        return $clientBuilder->httpCallback($httpCallback)->build();
    }

    public static function addTestConfiguration(ApiB4CClientBuilder $builder): ApiB4CClientBuilder
    {
        return $builder;
    }

    public static function addConfigurationFromEnvironment(ApiB4CClientBuilder $builder): ApiB4CClientBuilder
    {
        $timeout = getenv('API_B_4_C_LIB_TIMEOUT');
        $numberOfRetries = getenv('API_B_4_C_LIB_NUMBER_OF_RETRIES');
        $maximumRetryWaitTime = getenv('API_B_4_C_LIB_MAXIMUM_RETRY_WAIT_TIME');
        $environment = getenv('API_B_4_C_LIB_ENVIRONMENT');
        $username = getenv('API_B_4_C_LIB_USERNAME');
        $password = getenv('API_B_4_C_LIB_PASSWORD');

        if (!empty($timeout) && \is_numeric($timeout)) {
            $builder->timeout(intval($timeout));
        }

        if (!empty($numberOfRetries) && \is_numeric($numberOfRetries)) {
            $builder->numberOfRetries(intval($numberOfRetries));
        }

        if (!empty($maximumRetryWaitTime) && \is_numeric($maximumRetryWaitTime)) {
            $builder->maximumRetryWaitTime(intval($maximumRetryWaitTime));
        }

        if (!empty($environment)) {
            $builder->environment($environment);
        }

        if (!empty($username) && !empty($password)) {
            $builder->basicAuthCredentials(BasicAuthCredentialsBuilder::init($username, $password));
        }

        return $builder;
    }
}
