<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\AtualizarCampanhaRequest3;
use Core\Utils\CoreHelper;

/**
 * Builder for model AtualizarCampanhaRequest3
 *
 * @see AtualizarCampanhaRequest3
 */
class AtualizarCampanhaRequest3Builder
{
    /**
     * @var AtualizarCampanhaRequest3
     */
    private $instance;

    private function __construct(AtualizarCampanhaRequest3 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Atualizar Campanha Request 3 Builder object.
     *
     * @param int $idCampanhaPromocional
     * @param string $nomeCampanhaPromocional
     * @param string $inicioCampanhaPromocional
     * @param string $fimCampanhaPromocional
     * @param string $priorididadeCampanhaPromocional
     * @param int $tipoCampanhaPromocional
     */
    public static function init(
        int $idCampanhaPromocional,
        string $nomeCampanhaPromocional,
        string $inicioCampanhaPromocional,
        string $fimCampanhaPromocional,
        string $priorididadeCampanhaPromocional,
        int $tipoCampanhaPromocional
    ): self {
        return new self(new AtualizarCampanhaRequest3(
            $idCampanhaPromocional,
            $nomeCampanhaPromocional,
            $inicioCampanhaPromocional,
            $fimCampanhaPromocional,
            $priorididadeCampanhaPromocional,
            $tipoCampanhaPromocional
        ));
    }

    /**
     * Initializes a new Atualizar Campanha Request 3 object.
     */
    public function build(): AtualizarCampanhaRequest3
    {
        return CoreHelper::clone($this->instance);
    }
}
