<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\AtualizarCampanha;
use Core\Utils\CoreHelper;

/**
 * Builder for model AtualizarCampanha
 *
 * @see AtualizarCampanha
 */
class AtualizarCampanhaBuilder
{
    /**
     * @var AtualizarCampanha
     */
    private $instance;

    private function __construct(AtualizarCampanha $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Atualizar Campanha Builder object.
     *
     * @param string $message
     * @param string $responseCode
     */
    public static function init(string $message, string $responseCode): self
    {
        return new self(new AtualizarCampanha($message, $responseCode));
    }

    /**
     * Initializes a new Atualizar Campanha object.
     */
    public function build(): AtualizarCampanha
    {
        return CoreHelper::clone($this->instance);
    }
}
