<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\AtualizarOfertaRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model AtualizarOfertaRequest
 *
 * @see AtualizarOfertaRequest
 */
class AtualizarOfertaRequestBuilder
{
    /**
     * @var AtualizarOfertaRequest
     */
    private $instance;

    private function __construct(AtualizarOfertaRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Atualizar Oferta Request Builder object.
     *
     * @param string $nomeBrinde
     * @param string $qtdeBrindes
     * @param int $statusBrindesOferta
     */
    public static function init(string $nomeBrinde, string $qtdeBrindes, int $statusBrindesOferta): self
    {
        return new self(new AtualizarOfertaRequest($nomeBrinde, $qtdeBrindes, $statusBrindesOferta));
    }

    /**
     * Initializes a new Atualizar Oferta Request object.
     */
    public function build(): AtualizarOfertaRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
