<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\AtualizaEntregaRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model AtualizaEntregaRequest
 *
 * @see AtualizaEntregaRequest
 */
class AtualizaEntregaRequestBuilder
{
    /**
     * @var AtualizaEntregaRequest
     */
    private $instance;

    private function __construct(AtualizaEntregaRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Atualiza Entrega Request Builder object.
     *
     * @param string $rastreio
     * @param string $dataEnvio
     * @param string $dataEntrega
     * @param string $data
     * @param string $operacao
     * @param string $numero
     * @param string $nf
     * @param string $urlDownload
     */
    public static function init(
        string $rastreio,
        string $dataEnvio,
        string $dataEntrega,
        string $data,
        string $operacao,
        string $numero,
        string $nf,
        string $urlDownload
    ): self {
        return new self(new AtualizaEntregaRequest(
            $rastreio,
            $dataEnvio,
            $dataEntrega,
            $data,
            $operacao,
            $numero,
            $nf,
            $urlDownload
        ));
    }

    /**
     * Initializes a new Atualiza Entrega Request object.
     */
    public function build(): AtualizaEntregaRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
