<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\AtualizarMarcaRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model AtualizarMarcaRequest
 *
 * @see AtualizarMarcaRequest
 */
class AtualizarMarcaRequestBuilder
{
    /**
     * @var AtualizarMarcaRequest
     */
    private $instance;

    private function __construct(AtualizarMarcaRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Atualizar Marca Request Builder object.
     *
     * @param string $descricao
     * @param int $status
     */
    public static function init(string $descricao, int $status): self
    {
        return new self(new AtualizarMarcaRequest($descricao, $status));
    }

    /**
     * Initializes a new Atualizar Marca Request object.
     */
    public function build(): AtualizarMarcaRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
