<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\AtualizarCampanhaRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model AtualizarCampanhaRequest
 *
 * @see AtualizarCampanhaRequest
 */
class AtualizarCampanhaRequestBuilder
{
    /**
     * @var AtualizarCampanhaRequest
     */
    private $instance;

    private function __construct(AtualizarCampanhaRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Atualizar Campanha Request Builder object.
     *
     * @param string $nomeCampanhaPromocional
     * @param string $inicioCampanhaPromocional
     * @param string $fimCampanhaPromocional
     * @param string $priorididadeCampanhaPromocional
     */
    public static function init(
        string $nomeCampanhaPromocional,
        string $inicioCampanhaPromocional,
        string $fimCampanhaPromocional,
        string $priorididadeCampanhaPromocional
    ): self {
        return new self(new AtualizarCampanhaRequest(
            $nomeCampanhaPromocional,
            $inicioCampanhaPromocional,
            $fimCampanhaPromocional,
            $priorididadeCampanhaPromocional
        ));
    }

    /**
     * Initializes a new Atualizar Campanha Request object.
     */
    public function build(): AtualizarCampanhaRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
