<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\AtualizarCampanhaRequest2;
use Core\Utils\CoreHelper;

/**
 * Builder for model AtualizarCampanhaRequest2
 *
 * @see AtualizarCampanhaRequest2
 */
class AtualizarCampanhaRequest2Builder
{
    /**
     * @var AtualizarCampanhaRequest2
     */
    private $instance;

    private function __construct(AtualizarCampanhaRequest2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Atualizar Campanha Request 2 Builder object.
     *
     * @param string $nomeCampanhaLevemais
     * @param string $inicioCampanhaLevemais
     * @param string $fimCampanhaLevemais
     * @param int $prioridadeCampanhaLevemais
     * @param int $comprandoProdutos
     * @param int $numeroProdutosBeneficio
     * @param int $percentualDesconto
     * @param int $statusCampanhaLevemais
     */
    public static function init(
        string $nomeCampanhaLevemais,
        string $inicioCampanhaLevemais,
        string $fimCampanhaLevemais,
        int $prioridadeCampanhaLevemais,
        int $comprandoProdutos,
        int $numeroProdutosBeneficio,
        int $percentualDesconto,
        int $statusCampanhaLevemais
    ): self {
        return new self(new AtualizarCampanhaRequest2(
            $nomeCampanhaLevemais,
            $inicioCampanhaLevemais,
            $fimCampanhaLevemais,
            $prioridadeCampanhaLevemais,
            $comprandoProdutos,
            $numeroProdutosBeneficio,
            $percentualDesconto,
            $statusCampanhaLevemais
        ));
    }

    /**
     * Initializes a new Atualizar Campanha Request 2 object.
     */
    public function build(): AtualizarCampanhaRequest2
    {
        return CoreHelper::clone($this->instance);
    }
}
