<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\AtualizarDescontoRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model AtualizarDescontoRequest
 *
 * @see AtualizarDescontoRequest
 */
class AtualizarDescontoRequestBuilder
{
    /**
     * @var AtualizarDescontoRequest
     */
    private $instance;

    private function __construct(AtualizarDescontoRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Atualizar Desconto Request Builder object.
     *
     * @param string $titulo
     * @param int $tipoDesconto
     * @param int $desconto
     * @param string $inicio
     * @param string $fim
     */
    public static function init(string $titulo, int $tipoDesconto, int $desconto, string $inicio, string $fim): self
    {
        return new self(new AtualizarDescontoRequest($titulo, $tipoDesconto, $desconto, $inicio, $fim));
    }

    /**
     * Initializes a new Atualizar Desconto Request object.
     */
    public function build(): AtualizarDescontoRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
