<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\AtualizarEstoqueRequest;
use ApiB4CLib\Models\Estoque;
use ApiB4CLib\Models\EstoquesRetira2;
use Core\Utils\CoreHelper;

/**
 * Builder for model AtualizarEstoqueRequest
 *
 * @see AtualizarEstoqueRequest
 */
class AtualizarEstoqueRequestBuilder
{
    /**
     * @var AtualizarEstoqueRequest
     */
    private $instance;

    private function __construct(AtualizarEstoqueRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Atualizar Estoque Request Builder object.
     *
     * @param Estoque[] $estoques
     * @param EstoquesRetira2[] $estoquesRetira
     */
    public static function init(array $estoques, array $estoquesRetira): self
    {
        return new self(new AtualizarEstoqueRequest($estoques, $estoquesRetira));
    }

    /**
     * Initializes a new Atualizar Estoque Request object.
     */
    public function build(): AtualizarEstoqueRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
