<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\Brindes1;
use ApiB4CLib\Models\CadastraBrindesRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model CadastraBrindesRequest
 *
 * @see CadastraBrindesRequest
 */
class CadastraBrindesRequestBuilder
{
    /**
     * @var CadastraBrindesRequest
     */
    private $instance;

    private function __construct(CadastraBrindesRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cadastra Brindes Request Builder object.
     *
     * @param Brindes1[] $brindes
     */
    public static function init(array $brindes): self
    {
        return new self(new CadastraBrindesRequest($brindes));
    }

    /**
     * Initializes a new Cadastra Brindes Request object.
     */
    public function build(): CadastraBrindesRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
