<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\Brindes1;
use ApiB4CLib\Models\CadastraMarcaRequest;
use ApiB4CLib\Models\Marca1;
use Core\Utils\CoreHelper;

/**
 * Builder for model CadastraMarcaRequest
 *
 * @see CadastraMarcaRequest
 */
class CadastraMarcaRequestBuilder
{
    /**
     * @var CadastraMarcaRequest
     */
    private $instance;

    private function __construct(CadastraMarcaRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cadastra Marca Request Builder object.
     *
     * @param int $tipo
     * @param string $valorTotal
     * @param Marca1[] $marcas
     * @param Brindes1[] $brindes
     */
    public static function init(int $tipo, string $valorTotal, array $marcas, array $brindes): self
    {
        return new self(new CadastraMarcaRequest($tipo, $valorTotal, $marcas, $brindes));
    }

    /**
     * Initializes a new Cadastra Marca Request object.
     */
    public function build(): CadastraMarcaRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
