<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\CadastraCampanha1;
use Core\Utils\CoreHelper;

/**
 * Builder for model CadastraCampanha1
 *
 * @see CadastraCampanha1
 */
class CadastraCampanha1Builder
{
    /**
     * @var CadastraCampanha1
     */
    private $instance;

    private function __construct(CadastraCampanha1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cadastra Campanha 1 Builder object.
     *
     * @param string $message
     * @param string $responseCode
     */
    public static function init(string $message, string $responseCode): self
    {
        return new self(new CadastraCampanha1($message, $responseCode));
    }

    /**
     * Initializes a new Cadastra Campanha 1 object.
     */
    public function build(): CadastraCampanha1
    {
        return CoreHelper::clone($this->instance);
    }
}
