<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\CadastraPrecoRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model CadastraPrecoRequest
 *
 * @see CadastraPrecoRequest
 */
class CadastraPrecoRequestBuilder
{
    /**
     * @var CadastraPrecoRequest
     */
    private $instance;

    private function __construct(CadastraPrecoRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cadastra Preco Request Builder object.
     *
     * @param int $idCampanhaPromocional
     * @param int $preco
     */
    public static function init(int $idCampanhaPromocional, int $preco): self
    {
        return new self(new CadastraPrecoRequest($idCampanhaPromocional, $preco));
    }

    /**
     * Initializes a new Cadastra Preco Request object.
     */
    public function build(): CadastraPrecoRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
