<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\CadastrarAcessorioRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model CadastrarAcessorioRequest
 *
 * @see CadastrarAcessorioRequest
 */
class CadastrarAcessorioRequestBuilder
{
    /**
     * @var CadastrarAcessorioRequest
     */
    private $instance;

    private function __construct(CadastrarAcessorioRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cadastrar Acessorio Request Builder object.
     *
     * @param string $produtoSku
     * @param string $acessorioSku
     * @param string $base64
     */
    public static function init(string $produtoSku, string $acessorioSku, string $base64): self
    {
        return new self(new CadastrarAcessorioRequest($produtoSku, $acessorioSku, $base64));
    }

    /**
     * Initializes a new Cadastrar Acessorio Request object.
     */
    public function build(): CadastrarAcessorioRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
