<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\CadastraPreco1;
use Core\Utils\CoreHelper;

/**
 * Builder for model CadastraPreco1
 *
 * @see CadastraPreco1
 */
class CadastraPreco1Builder
{
    /**
     * @var CadastraPreco1
     */
    private $instance;

    private function __construct(CadastraPreco1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cadastra Preco 1 Builder object.
     *
     * @param string $message
     * @param string $responseCode
     */
    public static function init(string $message, string $responseCode): self
    {
        return new self(new CadastraPreco1($message, $responseCode));
    }

    /**
     * Initializes a new Cadastra Preco 1 object.
     */
    public function build(): CadastraPreco1
    {
        return CoreHelper::clone($this->instance);
    }
}
