<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\CadastrarUsuario;
use Core\Utils\CoreHelper;

/**
 * Builder for model CadastrarUsuario
 *
 * @see CadastrarUsuario
 */
class CadastrarUsuarioBuilder
{
    /**
     * @var CadastrarUsuario
     */
    private $instance;

    private function __construct(CadastrarUsuario $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cadastrar Usuario Builder object.
     *
     * @param string $message
     * @param string $responseCode
     */
    public static function init(string $message, string $responseCode): self
    {
        return new self(new CadastrarUsuario($message, $responseCode));
    }

    /**
     * Initializes a new Cadastrar Usuario object.
     */
    public function build(): CadastrarUsuario
    {
        return CoreHelper::clone($this->instance);
    }
}
