<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\CadastraOfertaRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model CadastraOfertaRequest
 *
 * @see CadastraOfertaRequest
 */
class CadastraOfertaRequestBuilder
{
    /**
     * @var CadastraOfertaRequest
     */
    private $instance;

    private function __construct(CadastraOfertaRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cadastra Oferta Request Builder object.
     *
     * @param string $idCampanhaBrindes
     * @param string $idOferta
     * @param string $nomeBrinde
     * @param string $qtdeBrindes
     */
    public static function init(
        string $idCampanhaBrindes,
        string $idOferta,
        string $nomeBrinde,
        string $qtdeBrindes
    ): self {
        return new self(new CadastraOfertaRequest($idCampanhaBrindes, $idOferta, $nomeBrinde, $qtdeBrindes));
    }

    /**
     * Initializes a new Cadastra Oferta Request object.
     */
    public function build(): CadastraOfertaRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
