<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\Brinde;
use ApiB4CLib\Models\CadastraProdutosRequest;
use ApiB4CLib\Models\Produto;
use Core\Utils\CoreHelper;

/**
 * Builder for model CadastraProdutosRequest
 *
 * @see CadastraProdutosRequest
 */
class CadastraProdutosRequestBuilder
{
    /**
     * @var CadastraProdutosRequest
     */
    private $instance;

    private function __construct(CadastraProdutosRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cadastra Produtos Request Builder object.
     *
     * @param Produto[] $produtos
     * @param Brinde[] $brindes
     */
    public static function init(array $produtos, array $brindes): self
    {
        return new self(new CadastraProdutosRequest($produtos, $brindes));
    }

    /**
     * Initializes a new Cadastra Produtos Request object.
     */
    public function build(): CadastraProdutosRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
