<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\CadastrarCategoriaRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model CadastrarCategoriaRequest
 *
 * @see CadastrarCategoriaRequest
 */
class CadastrarCategoriaRequestBuilder
{
    /**
     * @var CadastrarCategoriaRequest
     */
    private $instance;

    private function __construct(CadastrarCategoriaRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cadastrar Categoria Request Builder object.
     *
     * @param string $codigo
     * @param string $descricao
     * @param string $codigoPai
     */
    public static function init(string $codigo, string $descricao, string $codigoPai): self
    {
        return new self(new CadastrarCategoriaRequest($codigo, $descricao, $codigoPai));
    }

    /**
     * Initializes a new Cadastrar Categoria Request object.
     */
    public function build(): CadastrarCategoriaRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
