<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\CadastraCampanhaRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model CadastraCampanhaRequest
 *
 * @see CadastraCampanhaRequest
 */
class CadastraCampanhaRequestBuilder
{
    /**
     * @var CadastraCampanhaRequest
     */
    private $instance;

    private function __construct(CadastraCampanhaRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cadastra Campanha Request Builder object.
     *
     * @param string $idCampanhaPromocional
     * @param string $nomeCampanhaPromocional
     * @param string $inicioCampanhaPromocional
     * @param string $fimCampanhaPromocional
     * @param string $priorididadeCampanhaPromocional
     */
    public static function init(
        string $idCampanhaPromocional,
        string $nomeCampanhaPromocional,
        string $inicioCampanhaPromocional,
        string $fimCampanhaPromocional,
        string $priorididadeCampanhaPromocional
    ): self {
        return new self(new CadastraCampanhaRequest(
            $idCampanhaPromocional,
            $nomeCampanhaPromocional,
            $inicioCampanhaPromocional,
            $fimCampanhaPromocional,
            $priorididadeCampanhaPromocional
        ));
    }

    /**
     * Initializes a new Cadastra Campanha Request object.
     */
    public function build(): CadastraCampanhaRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
