<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\CadastrarFilial;
use Core\Utils\CoreHelper;

/**
 * Builder for model CadastrarFilial
 *
 * @see CadastrarFilial
 */
class CadastrarFilialBuilder
{
    /**
     * @var CadastrarFilial
     */
    private $instance;

    private function __construct(CadastrarFilial $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cadastrar Filial Builder object.
     *
     * @param string $message
     * @param string $responseCode
     */
    public static function init(string $message, string $responseCode): self
    {
        return new self(new CadastrarFilial($message, $responseCode));
    }

    /**
     * Initializes a new Cadastrar Filial object.
     */
    public function build(): CadastrarFilial
    {
        return CoreHelper::clone($this->instance);
    }
}
