<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\CadastrarDescontoRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model CadastrarDescontoRequest
 *
 * @see CadastrarDescontoRequest
 */
class CadastrarDescontoRequestBuilder
{
    /**
     * @var CadastrarDescontoRequest
     */
    private $instance;

    private function __construct(CadastrarDescontoRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cadastrar Desconto Request Builder object.
     *
     * @param string $cpfCnpj
     * @param string $titulo
     * @param int $tipoDesconto
     * @param int $desconto
     * @param string $inicio
     * @param string $fim
     */
    public static function init(
        string $cpfCnpj,
        string $titulo,
        int $tipoDesconto,
        int $desconto,
        string $inicio,
        string $fim
    ): self {
        return new self(new CadastrarDescontoRequest($cpfCnpj, $titulo, $tipoDesconto, $desconto, $inicio, $fim));
    }

    /**
     * Initializes a new Cadastrar Desconto Request object.
     */
    public function build(): CadastrarDescontoRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
