<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\CadastrarAcessorio;
use Core\Utils\CoreHelper;

/**
 * Builder for model CadastrarAcessorio
 *
 * @see CadastrarAcessorio
 */
class CadastrarAcessorioBuilder
{
    /**
     * @var CadastrarAcessorio
     */
    private $instance;

    private function __construct(CadastrarAcessorio $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cadastrar Acessorio Builder object.
     *
     * @param string $message
     * @param string $responseCode
     */
    public static function init(string $message, string $responseCode): self
    {
        return new self(new CadastrarAcessorio($message, $responseCode));
    }

    /**
     * Initializes a new Cadastrar Acessorio object.
     */
    public function build(): CadastrarAcessorio
    {
        return CoreHelper::clone($this->instance);
    }
}
