<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\CadastrarMarcaRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model CadastrarMarcaRequest
 *
 * @see CadastrarMarcaRequest
 */
class CadastrarMarcaRequestBuilder
{
    /**
     * @var CadastrarMarcaRequest
     */
    private $instance;

    private function __construct(CadastrarMarcaRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cadastrar Marca Request Builder object.
     *
     * @param string $codigo
     * @param string $descricao
     */
    public static function init(string $codigo, string $descricao): self
    {
        return new self(new CadastrarMarcaRequest($codigo, $descricao));
    }

    /**
     * Initializes a new Cadastrar Marca Request object.
     */
    public function build(): CadastrarMarcaRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
