<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\Categoria1;
use Core\Utils\CoreHelper;

/**
 * Builder for model Categoria1
 *
 * @see Categoria1
 */
class Categoria1Builder
{
    /**
     * @var Categoria1
     */
    private $instance;

    private function __construct(Categoria1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Categoria 1 Builder object.
     *
     * @param string $id
     * @param string $quantidade
     */
    public static function init(string $id, string $quantidade): self
    {
        return new self(new Categoria1($id, $quantidade));
    }

    /**
     * Initializes a new Categoria 1 object.
     */
    public function build(): Categoria1
    {
        return CoreHelper::clone($this->instance);
    }
}
