<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\Categoria2;
use Core\Utils\CoreHelper;

/**
 * Builder for model Categoria2
 *
 * @see Categoria2
 */
class Categoria2Builder
{
    /**
     * @var Categoria2
     */
    private $instance;

    private function __construct(Categoria2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Categoria 2 Builder object.
     *
     * @param string $id
     */
    public static function init(string $id): self
    {
        return new self(new Categoria2($id));
    }

    /**
     * Initializes a new Categoria 2 object.
     */
    public function build(): Categoria2
    {
        return CoreHelper::clone($this->instance);
    }
}
