<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\ConsultaFilial;
use Core\Utils\CoreHelper;

/**
 * Builder for model ConsultaFilial
 *
 * @see ConsultaFilial
 */
class ConsultaFilialBuilder
{
    /**
     * @var ConsultaFilial
     */
    private $instance;

    private function __construct(ConsultaFilial $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Consulta Filial Builder object.
     *
     * @param string $codigo
     * @param string $nome
     * @param string $razaoSocial
     * @param string $cnpj
     * @param string $cep
     * @param string $endereco
     * @param string $numero
     * @param string $complemento
     * @param string $bairro
     * @param string $cidade
     * @param string $uf
     * @param string $fone
     * @param string $fone2
     * @param string $urlGoogleMaps
     * @param string $urlVideoYoutube
     * @param string $possuiEstacionamento
     * @param string $horarioAtendimento
     * @param string $status
     */
    public static function init(
        string $codigo,
        string $nome,
        string $razaoSocial,
        string $cnpj,
        string $cep,
        string $endereco,
        string $numero,
        string $complemento,
        string $bairro,
        string $cidade,
        string $uf,
        string $fone,
        string $fone2,
        string $urlGoogleMaps,
        string $urlVideoYoutube,
        string $possuiEstacionamento,
        string $horarioAtendimento,
        string $status
    ): self {
        return new self(new ConsultaFilial(
            $codigo,
            $nome,
            $razaoSocial,
            $cnpj,
            $cep,
            $endereco,
            $numero,
            $complemento,
            $bairro,
            $cidade,
            $uf,
            $fone,
            $fone2,
            $urlGoogleMaps,
            $urlVideoYoutube,
            $possuiEstacionamento,
            $horarioAtendimento,
            $status
        ));
    }

    /**
     * Initializes a new Consulta Filial object.
     */
    public function build(): ConsultaFilial
    {
        return CoreHelper::clone($this->instance);
    }
}
