<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\Brindes2;
use ApiB4CLib\Models\Campanha;
use ApiB4CLib\Models\ConsultaQuantidade;
use Core\Utils\CoreHelper;

/**
 * Builder for model ConsultaQuantidade
 *
 * @see ConsultaQuantidade
 */
class ConsultaQuantidadeBuilder
{
    /**
     * @var ConsultaQuantidade
     */
    private $instance;

    private function __construct(ConsultaQuantidade $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Consulta Quantidade Builder object.
     *
     * @param Campanha $campanha
     * @param Brindes2[] $brindes
     */
    public static function init(Campanha $campanha, array $brindes): self
    {
        return new self(new ConsultaQuantidade($campanha, $brindes));
    }

    /**
     * Initializes a new Consulta Quantidade object.
     */
    public function build(): ConsultaQuantidade
    {
        return CoreHelper::clone($this->instance);
    }
}
