<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\ConsultaCampanha;
use Core\Utils\CoreHelper;

/**
 * Builder for model ConsultaCampanha
 *
 * @see ConsultaCampanha
 */
class ConsultaCampanhaBuilder
{
    /**
     * @var ConsultaCampanha
     */
    private $instance;

    private function __construct(ConsultaCampanha $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Consulta Campanha Builder object.
     *
     * @param string $idCampanhaPromocional
     * @param string $statusCampanhaPromocional
     * @param string $nomeCampanhaPromocional
     * @param string $inicioCampanhaPromocional
     * @param string $fimCampanhaPromocional
     * @param string $priorididadeCampanhaPromocional
     * @param string $createdAt
     * @param string $updatedAt
     * @param string $gerarLink
     * @param string $regraAtivacao
     * @param string $diasSemana
     * @param string $inicioPeriodo
     * @param string $fimPeriodo
     * @param string $temporizador
     * @param string $padraoEtiquetas
     * @param string $urlFixa
     */
    public static function init(
        string $idCampanhaPromocional,
        string $statusCampanhaPromocional,
        string $nomeCampanhaPromocional,
        string $inicioCampanhaPromocional,
        string $fimCampanhaPromocional,
        string $priorididadeCampanhaPromocional,
        string $createdAt,
        string $updatedAt,
        string $gerarLink,
        string $regraAtivacao,
        string $diasSemana,
        string $inicioPeriodo,
        string $fimPeriodo,
        string $temporizador,
        string $padraoEtiquetas,
        string $urlFixa
    ): self {
        return new self(new ConsultaCampanha(
            $idCampanhaPromocional,
            $statusCampanhaPromocional,
            $nomeCampanhaPromocional,
            $inicioCampanhaPromocional,
            $fimCampanhaPromocional,
            $priorididadeCampanhaPromocional,
            $createdAt,
            $updatedAt,
            $gerarLink,
            $regraAtivacao,
            $diasSemana,
            $inicioPeriodo,
            $fimPeriodo,
            $temporizador,
            $padraoEtiquetas,
            $urlFixa
        ));
    }

    /**
     * Sets tipo campanha promocional field.
     *
     * @param string|null $value
     */
    public function tipoCampanhaPromocional(?string $value): self
    {
        $this->instance->setTipoCampanhaPromocional($value);
        return $this;
    }

    /**
     * Sets logo campanha promocional field.
     *
     * @param string|null $value
     */
    public function logoCampanhaPromocional(?string $value): self
    {
        $this->instance->setLogoCampanhaPromocional($value);
        return $this;
    }

    /**
     * Sets banner campanha promocional field.
     *
     * @param string|null $value
     */
    public function bannerCampanhaPromocional(?string $value): self
    {
        $this->instance->setBannerCampanhaPromocional($value);
        return $this;
    }

    /**
     * Sets obs campanha promocional field.
     *
     * @param string|null $value
     */
    public function obsCampanhaPromocional(?string $value): self
    {
        $this->instance->setObsCampanhaPromocional($value);
        return $this;
    }

    /**
     * Sets identificador campanha promocional field.
     *
     * @param string|null $value
     */
    public function identificadorCampanhaPromocional(?string $value): self
    {
        $this->instance->setIdentificadorCampanhaPromocional($value);
        return $this;
    }

    /**
     * Sets campanha vitrine field.
     *
     * @param string|null $value
     */
    public function campanhaVitrine(?string $value): self
    {
        $this->instance->setCampanhaVitrine($value);
        return $this;
    }

    /**
     * Sets campanha place field.
     *
     * @param string|null $value
     */
    public function campanhaPlace(?string $value): self
    {
        $this->instance->setCampanhaPlace($value);
        return $this;
    }

    /**
     * Sets campanha utms field.
     *
     * @param string|null $value
     */
    public function campanhaUtms(?string $value): self
    {
        $this->instance->setCampanhaUtms($value);
        return $this;
    }

    /**
     * Sets seo campanha field.
     *
     * @param string|null $value
     */
    public function seoCampanha(?string $value): self
    {
        $this->instance->setSeoCampanha($value);
        return $this;
    }

    /**
     * Sets bloquear place campanha field.
     *
     * @param string|null $value
     */
    public function bloquearPlaceCampanha(?string $value): self
    {
        $this->instance->setBloquearPlaceCampanha($value);
        return $this;
    }

    /**
     * Sets bloquear busca campanha field.
     *
     * @param string|null $value
     */
    public function bloquearBuscaCampanha(?string $value): self
    {
        $this->instance->setBloquearBuscaCampanha($value);
        return $this;
    }

    /**
     * Sets bloquear erp campanha field.
     *
     * @param string|null $value
     */
    public function bloquearErpCampanha(?string $value): self
    {
        $this->instance->setBloquearErpCampanha($value);
        return $this;
    }

    /**
     * Sets title field.
     *
     * @param string|null $value
     */
    public function title(?string $value): self
    {
        $this->instance->setTitle($value);
        return $this;
    }

    /**
     * Sets meta description field.
     *
     * @param string|null $value
     */
    public function metaDescription(?string $value): self
    {
        $this->instance->setMetaDescription($value);
        return $this;
    }

    /**
     * Initializes a new Consulta Campanha object.
     */
    public function build(): ConsultaCampanha
    {
        return CoreHelper::clone($this->instance);
    }
}
