<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\ConsultaOferta;
use Core\Utils\CoreHelper;

/**
 * Builder for model ConsultaOferta
 *
 * @see ConsultaOferta
 */
class ConsultaOfertaBuilder
{
    /**
     * @var ConsultaOferta
     */
    private $instance;

    private function __construct(ConsultaOferta $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Consulta Oferta Builder object.
     *
     * @param string $idOferta
     * @param string $campanhaBrindes
     * @param string $statusBrindesOferta
     * @param string $valorTotal
     * @param string $qtdeBrindes
     * @param string $tipoValor
     * @param string $nomeBrinde
     * @param string $quantidadeTotalCarrinho
     * @param string $valorTotalCarrinho
     */
    public static function init(
        string $idOferta,
        string $campanhaBrindes,
        string $statusBrindesOferta,
        string $valorTotal,
        string $qtdeBrindes,
        string $tipoValor,
        string $nomeBrinde,
        string $quantidadeTotalCarrinho,
        string $valorTotalCarrinho
    ): self {
        return new self(new ConsultaOferta(
            $idOferta,
            $campanhaBrindes,
            $statusBrindesOferta,
            $valorTotal,
            $qtdeBrindes,
            $tipoValor,
            $nomeBrinde,
            $quantidadeTotalCarrinho,
            $valorTotalCarrinho
        ));
    }

    /**
     * Initializes a new Consulta Oferta object.
     */
    public function build(): ConsultaOferta
    {
        return CoreHelper::clone($this->instance);
    }
}
