<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\ConsultaCampanha4;
use Core\Utils\CoreHelper;

/**
 * Builder for model ConsultaCampanha4
 *
 * @see ConsultaCampanha4
 */
class ConsultaCampanha4Builder
{
    /**
     * @var ConsultaCampanha4
     */
    private $instance;

    private function __construct(ConsultaCampanha4 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Consulta Campanha 4 Builder object.
     *
     * @param string $idCampanhaLevemais
     * @param string $statusCampanhaLevemais
     * @param string $nomeCampanhaLevemais
     * @param string $inicioCampanhaLevemais
     * @param string $fimCampanhaLevemais
     * @param string $prioridadeCampanhaLevemais
     * @param string $comprandoProdutos
     * @param string $numeroProdutosBeneficio
     * @param string $percentualDesconto
     */
    public static function init(
        string $idCampanhaLevemais,
        string $statusCampanhaLevemais,
        string $nomeCampanhaLevemais,
        string $inicioCampanhaLevemais,
        string $fimCampanhaLevemais,
        string $prioridadeCampanhaLevemais,
        string $comprandoProdutos,
        string $numeroProdutosBeneficio,
        string $percentualDesconto
    ): self {
        return new self(new ConsultaCampanha4(
            $idCampanhaLevemais,
            $statusCampanhaLevemais,
            $nomeCampanhaLevemais,
            $inicioCampanhaLevemais,
            $fimCampanhaLevemais,
            $prioridadeCampanhaLevemais,
            $comprandoProdutos,
            $numeroProdutosBeneficio,
            $percentualDesconto
        ));
    }

    /**
     * Initializes a new Consulta Campanha 4 object.
     */
    public function build(): ConsultaCampanha4
    {
        return CoreHelper::clone($this->instance);
    }
}
