<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\Brindes;
use ApiB4CLib\Models\ConsultaProdutos;
use ApiB4CLib\Models\Produtos;
use Core\Utils\CoreHelper;

/**
 * Builder for model ConsultaProdutos
 *
 * @see ConsultaProdutos
 */
class ConsultaProdutosBuilder
{
    /**
     * @var ConsultaProdutos
     */
    private $instance;

    private function __construct(ConsultaProdutos $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Consulta Produtos Builder object.
     *
     * @param Produtos $produtos
     * @param Brindes $brindes
     */
    public static function init(Produtos $produtos, Brindes $brindes): self
    {
        return new self(new ConsultaProdutos($produtos, $brindes));
    }

    /**
     * Initializes a new Consulta Produtos object.
     */
    public function build(): ConsultaProdutos
    {
        return CoreHelper::clone($this->instance);
    }
}
