<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\ConsultaPreco;
use Core\Utils\CoreHelper;

/**
 * Builder for model ConsultaPreco
 *
 * @see ConsultaPreco
 */
class ConsultaPrecoBuilder
{
    /**
     * @var ConsultaPreco
     */
    private $instance;

    private function __construct(ConsultaPreco $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Consulta Preco Builder object.
     *
     * @param int $idOferta
     * @param int $statusCampanhaOferta
     * @param int $campanhaOferta
     * @param int $tipoOfertaDesconto
     * @param float|int $valorOferta
     * @param int $produtoOfertaDesconto
     * @param int $regraAtivacaoValor
     */
    public static function init(
        int $idOferta,
        int $statusCampanhaOferta,
        int $campanhaOferta,
        int $tipoOfertaDesconto,
        $valorOferta,
        int $produtoOfertaDesconto,
        int $regraAtivacaoValor
    ): self {
        return new self(new ConsultaPreco(
            $idOferta,
            $statusCampanhaOferta,
            $campanhaOferta,
            $tipoOfertaDesconto,
            $valorOferta,
            $produtoOfertaDesconto,
            $regraAtivacaoValor
        ));
    }

    /**
     * Sets agrupamento campanha oferta field.
     *
     * @param int|null|string|null $value
     */
    public function agrupamentoCampanhaOferta($value): self
    {
        $this->instance->setAgrupamentoCampanhaOferta($value);
        return $this;
    }

    /**
     * Sets prioridade atualizacao oferta field.
     *
     * @param string|null|int|null $value
     */
    public function prioridadeAtualizacaoOferta($value): self
    {
        $this->instance->setPrioridadeAtualizacaoOferta($value);
        return $this;
    }

    /**
     * Sets created at field.
     *
     * @param string|null $value
     */
    public function createdAt(?string $value): self
    {
        $this->instance->setCreatedAt($value);
        return $this;
    }

    /**
     * Sets updated at field.
     *
     * @param string|null $value
     */
    public function updatedAt(?string $value): self
    {
        $this->instance->setUpdatedAt($value);
        return $this;
    }

    /**
     * Sets preco atacado field.
     *
     * @param string|null $value
     */
    public function precoAtacado(?string $value): self
    {
        $this->instance->setPrecoAtacado($value);
        return $this;
    }

    /**
     * Initializes a new Consulta Preco object.
     */
    public function build(): ConsultaPreco
    {
        return CoreHelper::clone($this->instance);
    }
}
