<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\DadosDoCliente;
use Core\Utils\CoreHelper;

/**
 * Builder for model DadosDoCliente
 *
 * @see DadosDoCliente
 */
class DadosDoClienteBuilder
{
    /**
     * @var DadosDoCliente
     */
    private $instance;

    private function __construct(DadosDoCliente $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Dados Do Cliente Builder object.
     *
     * @param string $nome
     * @param int $tipo
     * @param string $cpfCnpj
     */
    public static function init(string $nome, int $tipo, string $cpfCnpj): self
    {
        return new self(new DadosDoCliente($nome, $tipo, $cpfCnpj));
    }

    /**
     * Initializes a new Dados Do Cliente object.
     */
    public function build(): DadosDoCliente
    {
        return CoreHelper::clone($this->instance);
    }
}
