<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\DeletarProdutosRequest1;
use Core\Utils\CoreHelper;

/**
 * Builder for model DeletarProdutosRequest1
 *
 * @see DeletarProdutosRequest1
 */
class DeletarProdutosRequest1Builder
{
    /**
     * @var DeletarProdutosRequest1
     */
    private $instance;

    private function __construct(DeletarProdutosRequest1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Deletar Produtos Request 1 Builder object.
     *
     * @param string[] $produtos
     */
    public static function init(array $produtos): self
    {
        return new self(new DeletarProdutosRequest1($produtos));
    }

    /**
     * Initializes a new Deletar Produtos Request 1 object.
     */
    public function build(): DeletarProdutosRequest1
    {
        return CoreHelper::clone($this->instance);
    }
}
