<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\Brindes1;
use ApiB4CLib\Models\DeletarBrindesRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model DeletarBrindesRequest
 *
 * @see DeletarBrindesRequest
 */
class DeletarBrindesRequestBuilder
{
    /**
     * @var DeletarBrindesRequest
     */
    private $instance;

    private function __construct(DeletarBrindesRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Deletar Brindes Request Builder object.
     *
     * @param Brindes1[] $brindes
     */
    public static function init(array $brindes): self
    {
        return new self(new DeletarBrindesRequest($brindes));
    }

    /**
     * Initializes a new Deletar Brindes Request object.
     */
    public function build(): DeletarBrindesRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
