<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\Brindes1;
use ApiB4CLib\Models\Categoria2;
use ApiB4CLib\Models\DeletarCategoriasRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model DeletarCategoriasRequest
 *
 * @see DeletarCategoriasRequest
 */
class DeletarCategoriasRequestBuilder
{
    /**
     * @var DeletarCategoriasRequest
     */
    private $instance;

    private function __construct(DeletarCategoriasRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Deletar Categorias Request Builder object.
     *
     * @param Categoria2[] $categorias
     * @param Brindes1[] $brindes
     */
    public static function init(array $categorias, array $brindes): self
    {
        return new self(new DeletarCategoriasRequest($categorias, $brindes));
    }

    /**
     * Initializes a new Deletar Categorias Request object.
     */
    public function build(): DeletarCategoriasRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
