<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\DeletarMarcaRequest;
use ApiB4CLib\Models\Marca2;
use Core\Utils\CoreHelper;

/**
 * Builder for model DeletarMarcaRequest
 *
 * @see DeletarMarcaRequest
 */
class DeletarMarcaRequestBuilder
{
    /**
     * @var DeletarMarcaRequest
     */
    private $instance;

    private function __construct(DeletarMarcaRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Deletar Marca Request Builder object.
     *
     * @param Marca2[] $marcas
     * @param array[] $brindes
     */
    public static function init(array $marcas, array $brindes): self
    {
        return new self(new DeletarMarcaRequest($marcas, $brindes));
    }

    /**
     * Initializes a new Deletar Marca Request object.
     */
    public function build(): DeletarMarcaRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
