<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\DeletarBrindes;
use Core\Utils\CoreHelper;

/**
 * Builder for model DeletarBrindes
 *
 * @see DeletarBrindes
 */
class DeletarBrindesBuilder
{
    /**
     * @var DeletarBrindes
     */
    private $instance;

    private function __construct(DeletarBrindes $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Deletar Brindes Builder object.
     *
     * @param string $message
     * @param string $responseCode
     */
    public static function init(string $message, string $responseCode): self
    {
        return new self(new DeletarBrindes($message, $responseCode));
    }

    /**
     * Initializes a new Deletar Brindes object.
     */
    public function build(): DeletarBrindes
    {
        return CoreHelper::clone($this->instance);
    }
}
