<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\EnviaEventosDoPedidoRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model EnviaEventosDoPedidoRequest
 *
 * @see EnviaEventosDoPedidoRequest
 */
class EnviaEventosDoPedidoRequestBuilder
{
    /**
     * @var EnviaEventosDoPedidoRequest
     */
    private $instance;

    private function __construct(EnviaEventosDoPedidoRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Envia Eventos Do Pedido Request Builder object.
     *
     * @param string $status
     * @param string $descricao
     */
    public static function init(string $status, string $descricao): self
    {
        return new self(new EnviaEventosDoPedidoRequest($status, $descricao));
    }

    /**
     * Initializes a new Envia Eventos Do Pedido Request object.
     */
    public function build(): EnviaEventosDoPedidoRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
