<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\EnviaNFPedido;
use Core\Utils\CoreHelper;

/**
 * Builder for model EnviaNFPedido
 *
 * @see EnviaNFPedido
 */
class EnviaNFPedidoBuilder
{
    /**
     * @var EnviaNFPedido
     */
    private $instance;

    private function __construct(EnviaNFPedido $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Envia NF Pedido Builder object.
     *
     * @param string $message
     * @param string $responseCode
     */
    public static function init(string $message, string $responseCode): self
    {
        return new self(new EnviaNFPedido($message, $responseCode));
    }

    /**
     * Initializes a new Envia NF Pedido object.
     */
    public function build(): EnviaNFPedido
    {
        return CoreHelper::clone($this->instance);
    }
}
