<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\EnviaEventosDaEntregaRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model EnviaEventosDaEntregaRequest
 *
 * @see EnviaEventosDaEntregaRequest
 */
class EnviaEventosDaEntregaRequestBuilder
{
    /**
     * @var EnviaEventosDaEntregaRequest
     */
    private $instance;

    private function __construct(EnviaEventosDaEntregaRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Envia Eventos Da Entrega Request Builder object.
     *
     * @param string $status
     * @param string $data
     */
    public static function init(string $status, string $data): self
    {
        return new self(new EnviaEventosDaEntregaRequest($status, $data));
    }

    /**
     * Initializes a new Envia Eventos Da Entrega Request object.
     */
    public function build(): EnviaEventosDaEntregaRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
