<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\EstoquesRetira2;
use Core\Utils\CoreHelper;

/**
 * Builder for model EstoquesRetira2
 *
 * @see EstoquesRetira2
 */
class EstoquesRetira2Builder
{
    /**
     * @var EstoquesRetira2
     */
    private $instance;

    private function __construct(EstoquesRetira2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Estoques Retira 2 Builder object.
     *
     * @param string $filialErp
     * @param string $quantidade
     * @param string $considerarEstoque
     */
    public static function init(string $filialErp, string $quantidade, string $considerarEstoque): self
    {
        return new self(new EstoquesRetira2($filialErp, $quantidade, $considerarEstoque));
    }

    /**
     * Initializes a new Estoques Retira 2 object.
     */
    public function build(): EstoquesRetira2
    {
        return CoreHelper::clone($this->instance);
    }
}
