<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\Faturamento;
use Core\Utils\CoreHelper;

/**
 * Builder for model Faturamento
 *
 * @see Faturamento
 */
class FaturamentoBuilder
{
    /**
     * @var Faturamento
     */
    private $instance;

    private function __construct(Faturamento $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Faturamento Builder object.
     *
     * @param int $unidade
     * @param int[] $logistica
     */
    public static function init(int $unidade, array $logistica): self
    {
        return new self(new Faturamento($unidade, $logistica));
    }

    /**
     * Initializes a new Faturamento object.
     */
    public function build(): Faturamento
    {
        return CoreHelper::clone($this->instance);
    }
}
