<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\InativarCampanha;
use Core\Utils\CoreHelper;

/**
 * Builder for model InativarCampanha
 *
 * @see InativarCampanha
 */
class InativarCampanhaBuilder
{
    /**
     * @var InativarCampanha
     */
    private $instance;

    private function __construct(InativarCampanha $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Inativar Campanha Builder object.
     *
     * @param string $message
     * @param string $responseCode
     */
    public static function init(string $message, string $responseCode): self
    {
        return new self(new InativarCampanha($message, $responseCode));
    }

    /**
     * Initializes a new Inativar Campanha object.
     */
    public function build(): InativarCampanha
    {
        return CoreHelper::clone($this->instance);
    }
}
