<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\InformacoesFiscais;
use Core\Utils\CoreHelper;

/**
 * Builder for model InformacoesFiscais
 *
 * @see InformacoesFiscais
 */
class InformacoesFiscaisBuilder
{
    /**
     * @var InformacoesFiscais
     */
    private $instance;

    private function __construct(InformacoesFiscais $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Informacoes Fiscais Builder object.
     *
     * @param string $cfop
     * @param string $ncm
     * @param string $cest
     * @param string $cst
     * @param string $icms
     * @param string $icmsSt
     * @param string $diferimentoParcial
     * @param string $mva
     * @param string $origem
     * @param string $tipoOrigem
     * @param string $csosn
     */
    public static function init(
        string $cfop,
        string $ncm,
        string $cest,
        string $cst,
        string $icms,
        string $icmsSt,
        string $diferimentoParcial,
        string $mva,
        string $origem,
        string $tipoOrigem,
        string $csosn
    ): self {
        return new self(new InformacoesFiscais(
            $cfop,
            $ncm,
            $cest,
            $cst,
            $icms,
            $icmsSt,
            $diferimentoParcial,
            $mva,
            $origem,
            $tipoOrigem,
            $csosn
        ));
    }

    /**
     * Sets ipi field.
     *
     * @param string|null $value
     */
    public function ipi(?string $value): self
    {
        $this->instance->setIpi($value);
        return $this;
    }

    /**
     * Sets reducao icms field.
     *
     * @param string|null $value
     */
    public function reducaoIcms(?string $value): self
    {
        $this->instance->setReducaoIcms($value);
        return $this;
    }

    /**
     * Initializes a new Informacoes Fiscais object.
     */
    public function build(): InformacoesFiscais
    {
        return CoreHelper::clone($this->instance);
    }
}
