<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\ListaUsuario;
use Core\Utils\CoreHelper;

/**
 * Builder for model ListaUsuario
 *
 * @see ListaUsuario
 */
class ListaUsuarioBuilder
{
    /**
     * @var ListaUsuario
     */
    private $instance;

    private function __construct(ListaUsuario $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Lista Usuario Builder object.
     *
     * @param string $codigo
     * @param string $nome
     * @param string $email
     * @param string $status
     * @param string $nivel
     */
    public static function init(string $codigo, string $nome, string $email, string $status, string $nivel): self
    {
        return new self(new ListaUsuario($codigo, $nome, $email, $status, $nivel));
    }

    /**
     * Initializes a new Lista Usuario object.
     */
    public function build(): ListaUsuario
    {
        return CoreHelper::clone($this->instance);
    }
}
