<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\Marca;
use Core\Utils\CoreHelper;

/**
 * Builder for model Marca
 *
 * @see Marca
 */
class MarcaBuilder
{
    /**
     * @var Marca
     */
    private $instance;

    private function __construct(Marca $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Marca Builder object.
     *
     * @param string $campanha
     * @param string $nome
     * @param string $quantidade
     */
    public static function init(string $campanha, string $nome, string $quantidade): self
    {
        return new self(new Marca($campanha, $nome, $quantidade));
    }

    /**
     * Initializes a new Marca object.
     */
    public function build(): Marca
    {
        return CoreHelper::clone($this->instance);
    }
}
