<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\NewRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model NewRequest
 *
 * @see NewRequest
 */
class NewRequestBuilder
{
    /**
     * @var NewRequest
     */
    private $instance;

    private function __construct(NewRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new New Request Builder object.
     *
     * @param string $message
     * @param string $responseCode
     */
    public static function init(string $message, string $responseCode): self
    {
        return new self(new NewRequest($message, $responseCode));
    }

    /**
     * Initializes a new New Request object.
     */
    public function build(): NewRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
