<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\NewRequest11;
use Core\Utils\CoreHelper;

/**
 * Builder for model NewRequest11
 *
 * @see NewRequest11
 */
class NewRequest11Builder
{
    /**
     * @var NewRequest11
     */
    private $instance;

    private function __construct(NewRequest11 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new New Request 11 Builder object.
     *
     * @param string $nome
     * @param int $tipo
     * @param string $cpfCnpj
     */
    public static function init(string $nome, int $tipo, string $cpfCnpj): self
    {
        return new self(new NewRequest11($nome, $tipo, $cpfCnpj));
    }

    /**
     * Initializes a new New Request 11 object.
     */
    public function build(): NewRequest11
    {
        return CoreHelper::clone($this->instance);
    }
}
