<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\NotasFiscai;
use Core\Utils\CoreHelper;

/**
 * Builder for model NotasFiscai
 *
 * @see NotasFiscai
 */
class NotasFiscaiBuilder
{
    /**
     * @var NotasFiscai
     */
    private $instance;

    private function __construct(NotasFiscai $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Notas Fiscai Builder object.
     *
     * @param string $data
     * @param string $tipo
     * @param string $numero
     * @param string $chave
     * @param string $xml
     * @param string $codigoFornecedor
     * @param string $urlDownload
     */
    public static function init(
        string $data,
        string $tipo,
        string $numero,
        string $chave,
        string $xml,
        string $codigoFornecedor,
        string $urlDownload
    ): self {
        return new self(new NotasFiscai($data, $tipo, $numero, $chave, $xml, $codigoFornecedor, $urlDownload));
    }

    /**
     * Initializes a new Notas Fiscai object.
     */
    public function build(): NotasFiscai
    {
        return CoreHelper::clone($this->instance);
    }
}
