<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\Produtos1;
use Core\Utils\CoreHelper;

/**
 * Builder for model Produtos1
 *
 * @see Produtos1
 */
class Produtos1Builder
{
    /**
     * @var Produtos1
     */
    private $instance;

    private function __construct(Produtos1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Produtos 1 Builder object.
     *
     * @param string $sku
     */
    public static function init(string $sku): self
    {
        return new self(new Produtos1($sku));
    }

    /**
     * Initializes a new Produtos 1 object.
     */
    public function build(): Produtos1
    {
        return CoreHelper::clone($this->instance);
    }
}
