<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\Produto;
use Core\Utils\CoreHelper;

/**
 * Builder for model Produto
 *
 * @see Produto
 */
class ProdutoBuilder
{
    /**
     * @var Produto
     */
    private $instance;

    private function __construct(Produto $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Produto Builder object.
     *
     * @param string $sku
     * @param string $quantidade
     */
    public static function init(string $sku, string $quantidade): self
    {
        return new self(new Produto($sku, $quantidade));
    }

    /**
     * Initializes a new Produto object.
     */
    public function build(): Produto
    {
        return CoreHelper::clone($this->instance);
    }
}
