<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models\Builders;

use ApiB4CLib\Models\StatusPedido;
use Core\Utils\CoreHelper;

/**
 * Builder for model StatusPedido
 *
 * @see StatusPedido
 */
class StatusPedidoBuilder
{
    /**
     * @var StatusPedido
     */
    private $instance;

    private function __construct(StatusPedido $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Status Pedido Builder object.
     *
     * @param string $codigo
     * @param string $status
     */
    public static function init(string $codigo, string $status): self
    {
        return new self(new StatusPedido($codigo, $status));
    }

    /**
     * Initializes a new Status Pedido object.
     */
    public function build(): StatusPedido
    {
        return CoreHelper::clone($this->instance);
    }
}
