<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Http;

use Core\Types\Sdk\CoreResponse;

/**
 * HTTP response received
 */
class HttpResponse extends CoreResponse
{
}
