<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Controllers;

use ApiB4CLib\Exceptions\ApiException;
use ApiB4CLib\Models\AtualizarRequest;
use ApiB4CLib\Models\CadastrarRequest;
use ApiB4CLib\Models\NewRequestRequest;
use Core\Request\Parameters\BodyParam;
use CoreInterfaces\Core\Request\RequestMethod;

class PersonalizacaoController extends BaseController
{
    /**
     * @param CadastrarRequest $body
     *
     * @return void Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function cadastrar(CadastrarRequest $body): void
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/tipo-personalizacao')
            ->auth('basic')
            ->parameters(BodyParam::init($body));

        $this->execute($_reqBuilder);
    }

    /**
     * @param AtualizarRequest $body
     *
     * @return void Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function atualizar(AtualizarRequest $body): void
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::PUT, '/tipo-personalizacao')
            ->auth('basic')
            ->parameters(BodyParam::init($body));

        $this->execute($_reqBuilder);
    }

    /**
     * @param NewRequestRequest $body
     *
     * @return void Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function newRequest(NewRequestRequest $body): void
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::DELETE, '/tipo-personalizacao')
            ->auth('basic')
            ->parameters(BodyParam::init($body));

        $this->execute($_reqBuilder);
    }
}
