<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Exceptions;

use ApiB4CLib\ApiHelper;

class DeletarPrecoException extends ApiException
{
    /**
     * @var string
     */
    private $messageProperty;

    /**
     * @var string
     */
    private $responseCode;

    /**
     * @param string $reason
     * @param \ApiB4CLib\Http\HttpRequest $request
     * @param \ApiB4CLib\Http\HttpResponse $response
     * @param string $messageProperty
     * @param string $responseCode
     */
    public function __construct(
        string $reason,
        \ApiB4CLib\Http\HttpRequest $request,
        \ApiB4CLib\Http\HttpResponse $response,
        string $messageProperty,
        string $responseCode
    ) {
        parent::__construct($reason, $request, $response);
        $this->messageProperty = $messageProperty;
        $this->responseCode = $responseCode;
    }

    /**
     * Returns Message Property.
     */
    public function getMessageProperty(): string
    {
        return $this->messageProperty;
    }

    /**
     * Sets Message Property.
     *
     * @required
     * @maps message
     */
    public function setMessageProperty(string $messageProperty): void
    {
        $this->messageProperty = $messageProperty;
    }

    /**
     * Returns Response Code.
     */
    public function getResponseCode(): string
    {
        return $this->responseCode;
    }

    /**
     * Sets Response Code.
     *
     * @required
     * @maps responseCode
     */
    public function setResponseCode(string $responseCode): void
    {
        $this->responseCode = $responseCode;
    }

    /**
     * Converts the DeletarPrecoException object to a human-readable string representation.
     *
     * @return string The string representation of the DeletarPrecoException object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'DeletarPrecoException',
            ['messageProperty' => $this->messageProperty, 'responseCode' => $this->responseCode],
            parent::__toString()
        );
    }
}
