<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models;

use ApiB4CLib\ApiHelper;
use stdClass;

class Atributo implements \JsonSerializable
{
    /**
     * @var string
     */
    private $nome;

    /**
     * @var string
     */
    private $valor;

    /**
     * @param string $nome
     * @param string $valor
     */
    public function __construct(string $nome, string $valor)
    {
        $this->nome = $nome;
        $this->valor = $valor;
    }

    /**
     * Returns Nome.
     */
    public function getNome(): string
    {
        return $this->nome;
    }

    /**
     * Sets Nome.
     *
     * @required
     * @maps nome
     */
    public function setNome(string $nome): void
    {
        $this->nome = $nome;
    }

    /**
     * Returns Valor.
     */
    public function getValor(): string
    {
        return $this->valor;
    }

    /**
     * Sets Valor.
     *
     * @required
     * @maps valor
     */
    public function setValor(string $valor): void
    {
        $this->valor = $valor;
    }

    /**
     * Converts the Atributo object to a human-readable string representation.
     *
     * @return string The string representation of the Atributo object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('Atributo', ['nome' => $this->nome, 'valor' => $this->valor]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['nome']  = $this->nome;
        $json['valor'] = $this->valor;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
