<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models;

use ApiB4CLib\ApiHelper;
use stdClass;

class AtualizaEntregaRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $rastreio;

    /**
     * @var string
     */
    private $dataEnvio;

    /**
     * @var string
     */
    private $dataEntrega;

    /**
     * @var string
     */
    private $data;

    /**
     * @var string
     */
    private $operacao;

    /**
     * @var string
     */
    private $numero;

    /**
     * @var string
     */
    private $nf;

    /**
     * @var string
     */
    private $urlDownload;

    /**
     * @param string $rastreio
     * @param string $dataEnvio
     * @param string $dataEntrega
     * @param string $data
     * @param string $operacao
     * @param string $numero
     * @param string $nf
     * @param string $urlDownload
     */
    public function __construct(
        string $rastreio,
        string $dataEnvio,
        string $dataEntrega,
        string $data,
        string $operacao,
        string $numero,
        string $nf,
        string $urlDownload
    ) {
        $this->rastreio = $rastreio;
        $this->dataEnvio = $dataEnvio;
        $this->dataEntrega = $dataEntrega;
        $this->data = $data;
        $this->operacao = $operacao;
        $this->numero = $numero;
        $this->nf = $nf;
        $this->urlDownload = $urlDownload;
    }

    /**
     * Returns Rastreio.
     */
    public function getRastreio(): string
    {
        return $this->rastreio;
    }

    /**
     * Sets Rastreio.
     *
     * @required
     * @maps rastreio
     */
    public function setRastreio(string $rastreio): void
    {
        $this->rastreio = $rastreio;
    }

    /**
     * Returns Data Envio.
     */
    public function getDataEnvio(): string
    {
        return $this->dataEnvio;
    }

    /**
     * Sets Data Envio.
     *
     * @required
     * @maps data_envio
     */
    public function setDataEnvio(string $dataEnvio): void
    {
        $this->dataEnvio = $dataEnvio;
    }

    /**
     * Returns Data Entrega.
     */
    public function getDataEntrega(): string
    {
        return $this->dataEntrega;
    }

    /**
     * Sets Data Entrega.
     *
     * @required
     * @maps data_entrega
     */
    public function setDataEntrega(string $dataEntrega): void
    {
        $this->dataEntrega = $dataEntrega;
    }

    /**
     * Returns Data.
     */
    public function getData(): string
    {
        return $this->data;
    }

    /**
     * Sets Data.
     *
     * @required
     * @maps data
     */
    public function setData(string $data): void
    {
        $this->data = $data;
    }

    /**
     * Returns Operacao.
     */
    public function getOperacao(): string
    {
        return $this->operacao;
    }

    /**
     * Sets Operacao.
     *
     * @required
     * @maps operacao
     */
    public function setOperacao(string $operacao): void
    {
        $this->operacao = $operacao;
    }

    /**
     * Returns Numero.
     */
    public function getNumero(): string
    {
        return $this->numero;
    }

    /**
     * Sets Numero.
     *
     * @required
     * @maps numero
     */
    public function setNumero(string $numero): void
    {
        $this->numero = $numero;
    }

    /**
     * Returns Nf.
     */
    public function getNf(): string
    {
        return $this->nf;
    }

    /**
     * Sets Nf.
     *
     * @required
     * @maps nf
     */
    public function setNf(string $nf): void
    {
        $this->nf = $nf;
    }

    /**
     * Returns Url Download.
     */
    public function getUrlDownload(): string
    {
        return $this->urlDownload;
    }

    /**
     * Sets Url Download.
     *
     * @required
     * @maps url_download
     */
    public function setUrlDownload(string $urlDownload): void
    {
        $this->urlDownload = $urlDownload;
    }

    /**
     * Converts the AtualizaEntregaRequest object to a human-readable string representation.
     *
     * @return string The string representation of the AtualizaEntregaRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AtualizaEntregaRequest',
            [
                'rastreio' => $this->rastreio,
                'dataEnvio' => $this->dataEnvio,
                'dataEntrega' => $this->dataEntrega,
                'data' => $this->data,
                'operacao' => $this->operacao,
                'numero' => $this->numero,
                'nf' => $this->nf,
                'urlDownload' => $this->urlDownload
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['rastreio']     = $this->rastreio;
        $json['data_envio']   = $this->dataEnvio;
        $json['data_entrega'] = $this->dataEntrega;
        $json['data']         = $this->data;
        $json['operacao']     = $this->operacao;
        $json['numero']       = $this->numero;
        $json['nf']           = $this->nf;
        $json['url_download'] = $this->urlDownload;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
