<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models;

use ApiB4CLib\ApiHelper;
use stdClass;

class AtualizaQuantidadeRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $valorTotalCarrinho;

    /**
     * @var string
     */
    private $quantidadeTotalCarrinho;

    /**
     * @param string $valorTotalCarrinho
     * @param string $quantidadeTotalCarrinho
     */
    public function __construct(string $valorTotalCarrinho, string $quantidadeTotalCarrinho)
    {
        $this->valorTotalCarrinho = $valorTotalCarrinho;
        $this->quantidadeTotalCarrinho = $quantidadeTotalCarrinho;
    }

    /**
     * Returns Valor Total Carrinho.
     */
    public function getValorTotalCarrinho(): string
    {
        return $this->valorTotalCarrinho;
    }

    /**
     * Sets Valor Total Carrinho.
     *
     * @required
     * @maps valor_total_carrinho
     */
    public function setValorTotalCarrinho(string $valorTotalCarrinho): void
    {
        $this->valorTotalCarrinho = $valorTotalCarrinho;
    }

    /**
     * Returns Quantidade Total Carrinho.
     */
    public function getQuantidadeTotalCarrinho(): string
    {
        return $this->quantidadeTotalCarrinho;
    }

    /**
     * Sets Quantidade Total Carrinho.
     *
     * @required
     * @maps quantidade_total_carrinho
     */
    public function setQuantidadeTotalCarrinho(string $quantidadeTotalCarrinho): void
    {
        $this->quantidadeTotalCarrinho = $quantidadeTotalCarrinho;
    }

    /**
     * Converts the AtualizaQuantidadeRequest object to a human-readable string representation.
     *
     * @return string The string representation of the AtualizaQuantidadeRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AtualizaQuantidadeRequest',
            [
                'valorTotalCarrinho' => $this->valorTotalCarrinho,
                'quantidadeTotalCarrinho' => $this->quantidadeTotalCarrinho
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['valor_total_carrinho']      = $this->valorTotalCarrinho;
        $json['quantidade_total_carrinho'] = $this->quantidadeTotalCarrinho;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
