<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models;

use ApiB4CLib\ApiHelper;
use stdClass;

class AtualizarMarcaRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $descricao;

    /**
     * @var int
     */
    private $status;

    /**
     * @param string $descricao
     * @param int $status
     */
    public function __construct(string $descricao, int $status)
    {
        $this->descricao = $descricao;
        $this->status = $status;
    }

    /**
     * Returns Descricao.
     */
    public function getDescricao(): string
    {
        return $this->descricao;
    }

    /**
     * Sets Descricao.
     *
     * @required
     * @maps descricao
     */
    public function setDescricao(string $descricao): void
    {
        $this->descricao = $descricao;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): int
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @required
     * @maps status
     */
    public function setStatus(int $status): void
    {
        $this->status = $status;
    }

    /**
     * Converts the AtualizarMarcaRequest object to a human-readable string representation.
     *
     * @return string The string representation of the AtualizarMarcaRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AtualizarMarcaRequest',
            ['descricao' => $this->descricao, 'status' => $this->status]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['descricao'] = $this->descricao;
        $json['status']    = $this->status;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
