<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models;

use ApiB4CLib\ApiHelper;
use stdClass;

class AtualizarEstoqueRequest implements \JsonSerializable
{
    /**
     * @var Estoque[]
     */
    private $estoques;

    /**
     * @var EstoquesRetira2[]
     */
    private $estoquesRetira;

    /**
     * @param Estoque[] $estoques
     * @param EstoquesRetira2[] $estoquesRetira
     */
    public function __construct(array $estoques, array $estoquesRetira)
    {
        $this->estoques = $estoques;
        $this->estoquesRetira = $estoquesRetira;
    }

    /**
     * Returns Estoques.
     *
     * @return Estoque[]
     */
    public function getEstoques(): array
    {
        return $this->estoques;
    }

    /**
     * Sets Estoques.
     *
     * @required
     * @maps estoques
     *
     * @param Estoque[] $estoques
     */
    public function setEstoques(array $estoques): void
    {
        $this->estoques = $estoques;
    }

    /**
     * Returns Estoques Retira.
     *
     * @return EstoquesRetira2[]
     */
    public function getEstoquesRetira(): array
    {
        return $this->estoquesRetira;
    }

    /**
     * Sets Estoques Retira.
     *
     * @required
     * @maps estoques_retira
     *
     * @param EstoquesRetira2[] $estoquesRetira
     */
    public function setEstoquesRetira(array $estoquesRetira): void
    {
        $this->estoquesRetira = $estoquesRetira;
    }

    /**
     * Converts the AtualizarEstoqueRequest object to a human-readable string representation.
     *
     * @return string The string representation of the AtualizarEstoqueRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AtualizarEstoqueRequest',
            ['estoques' => $this->estoques, 'estoquesRetira' => $this->estoquesRetira]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['estoques']        = $this->estoques;
        $json['estoques_retira'] = $this->estoquesRetira;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
