<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models;

use ApiB4CLib\ApiHelper;
use stdClass;

class CadastrarProdutoRequest1 implements \JsonSerializable
{
    /**
     * @var int
     */
    private $campanha;

    /**
     * @var string
     */
    private $sku;

    /**
     * @var int
     */
    private $quantidade;

    /**
     * @var int
     */
    private $desconto;

    /**
     * @param int $campanha
     * @param string $sku
     * @param int $quantidade
     * @param int $desconto
     */
    public function __construct(int $campanha, string $sku, int $quantidade, int $desconto)
    {
        $this->campanha = $campanha;
        $this->sku = $sku;
        $this->quantidade = $quantidade;
        $this->desconto = $desconto;
    }

    /**
     * Returns Campanha.
     */
    public function getCampanha(): int
    {
        return $this->campanha;
    }

    /**
     * Sets Campanha.
     *
     * @required
     * @maps campanha
     */
    public function setCampanha(int $campanha): void
    {
        $this->campanha = $campanha;
    }

    /**
     * Returns Sku.
     */
    public function getSku(): string
    {
        return $this->sku;
    }

    /**
     * Sets Sku.
     *
     * @required
     * @maps sku
     */
    public function setSku(string $sku): void
    {
        $this->sku = $sku;
    }

    /**
     * Returns Quantidade.
     */
    public function getQuantidade(): int
    {
        return $this->quantidade;
    }

    /**
     * Sets Quantidade.
     *
     * @required
     * @maps quantidade
     */
    public function setQuantidade(int $quantidade): void
    {
        $this->quantidade = $quantidade;
    }

    /**
     * Returns Desconto.
     */
    public function getDesconto(): int
    {
        return $this->desconto;
    }

    /**
     * Sets Desconto.
     *
     * @required
     * @maps desconto
     */
    public function setDesconto(int $desconto): void
    {
        $this->desconto = $desconto;
    }

    /**
     * Converts the CadastrarProdutoRequest1 object to a human-readable string representation.
     *
     * @return string The string representation of the CadastrarProdutoRequest1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CadastrarProdutoRequest1',
            [
                'campanha' => $this->campanha,
                'sku' => $this->sku,
                'quantidade' => $this->quantidade,
                'desconto' => $this->desconto
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['campanha']   = $this->campanha;
        $json['sku']        = $this->sku;
        $json['quantidade'] = $this->quantidade;
        $json['desconto']   = $this->desconto;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
