<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models;

use ApiB4CLib\ApiHelper;
use stdClass;

class CadastrarCategoriaRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $codigo;

    /**
     * @var string
     */
    private $descricao;

    /**
     * @var string
     */
    private $codigoPai;

    /**
     * @param string $codigo
     * @param string $descricao
     * @param string $codigoPai
     */
    public function __construct(string $codigo, string $descricao, string $codigoPai)
    {
        $this->codigo = $codigo;
        $this->descricao = $descricao;
        $this->codigoPai = $codigoPai;
    }

    /**
     * Returns Codigo.
     */
    public function getCodigo(): string
    {
        return $this->codigo;
    }

    /**
     * Sets Codigo.
     *
     * @required
     * @maps codigo
     */
    public function setCodigo(string $codigo): void
    {
        $this->codigo = $codigo;
    }

    /**
     * Returns Descricao.
     */
    public function getDescricao(): string
    {
        return $this->descricao;
    }

    /**
     * Sets Descricao.
     *
     * @required
     * @maps descricao
     */
    public function setDescricao(string $descricao): void
    {
        $this->descricao = $descricao;
    }

    /**
     * Returns Codigo Pai.
     */
    public function getCodigoPai(): string
    {
        return $this->codigoPai;
    }

    /**
     * Sets Codigo Pai.
     *
     * @required
     * @maps codigo_pai
     */
    public function setCodigoPai(string $codigoPai): void
    {
        $this->codigoPai = $codigoPai;
    }

    /**
     * Converts the CadastrarCategoriaRequest object to a human-readable string representation.
     *
     * @return string The string representation of the CadastrarCategoriaRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CadastrarCategoriaRequest',
            ['codigo' => $this->codigo, 'descricao' => $this->descricao, 'codigoPai' => $this->codigoPai]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['codigo']     = $this->codigo;
        $json['descricao']  = $this->descricao;
        $json['codigo_pai'] = $this->codigoPai;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
