<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models;

use ApiB4CLib\ApiHelper;
use stdClass;

class CadastrarDescontoRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $cpfCnpj;

    /**
     * @var string
     */
    private $titulo;

    /**
     * @var int
     */
    private $tipoDesconto;

    /**
     * @var int
     */
    private $desconto;

    /**
     * @var string
     */
    private $inicio;

    /**
     * @var string
     */
    private $fim;

    /**
     * @param string $cpfCnpj
     * @param string $titulo
     * @param int $tipoDesconto
     * @param int $desconto
     * @param string $inicio
     * @param string $fim
     */
    public function __construct(
        string $cpfCnpj,
        string $titulo,
        int $tipoDesconto,
        int $desconto,
        string $inicio,
        string $fim
    ) {
        $this->cpfCnpj = $cpfCnpj;
        $this->titulo = $titulo;
        $this->tipoDesconto = $tipoDesconto;
        $this->desconto = $desconto;
        $this->inicio = $inicio;
        $this->fim = $fim;
    }

    /**
     * Returns Cpf Cnpj.
     */
    public function getCpfCnpj(): string
    {
        return $this->cpfCnpj;
    }

    /**
     * Sets Cpf Cnpj.
     *
     * @required
     * @maps cpf_cnpj
     */
    public function setCpfCnpj(string $cpfCnpj): void
    {
        $this->cpfCnpj = $cpfCnpj;
    }

    /**
     * Returns Titulo.
     */
    public function getTitulo(): string
    {
        return $this->titulo;
    }

    /**
     * Sets Titulo.
     *
     * @required
     * @maps titulo
     */
    public function setTitulo(string $titulo): void
    {
        $this->titulo = $titulo;
    }

    /**
     * Returns Tipo Desconto.
     */
    public function getTipoDesconto(): int
    {
        return $this->tipoDesconto;
    }

    /**
     * Sets Tipo Desconto.
     *
     * @required
     * @maps tipo_desconto
     */
    public function setTipoDesconto(int $tipoDesconto): void
    {
        $this->tipoDesconto = $tipoDesconto;
    }

    /**
     * Returns Desconto.
     */
    public function getDesconto(): int
    {
        return $this->desconto;
    }

    /**
     * Sets Desconto.
     *
     * @required
     * @maps desconto
     */
    public function setDesconto(int $desconto): void
    {
        $this->desconto = $desconto;
    }

    /**
     * Returns Inicio.
     */
    public function getInicio(): string
    {
        return $this->inicio;
    }

    /**
     * Sets Inicio.
     *
     * @required
     * @maps inicio
     */
    public function setInicio(string $inicio): void
    {
        $this->inicio = $inicio;
    }

    /**
     * Returns Fim.
     */
    public function getFim(): string
    {
        return $this->fim;
    }

    /**
     * Sets Fim.
     *
     * @required
     * @maps fim
     */
    public function setFim(string $fim): void
    {
        $this->fim = $fim;
    }

    /**
     * Converts the CadastrarDescontoRequest object to a human-readable string representation.
     *
     * @return string The string representation of the CadastrarDescontoRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CadastrarDescontoRequest',
            [
                'cpfCnpj' => $this->cpfCnpj,
                'titulo' => $this->titulo,
                'tipoDesconto' => $this->tipoDesconto,
                'desconto' => $this->desconto,
                'inicio' => $this->inicio,
                'fim' => $this->fim
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['cpf_cnpj']      = $this->cpfCnpj;
        $json['titulo']        = $this->titulo;
        $json['tipo_desconto'] = $this->tipoDesconto;
        $json['desconto']      = $this->desconto;
        $json['inicio']        = $this->inicio;
        $json['fim']           = $this->fim;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
