<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models;

use ApiB4CLib\ApiHelper;
use stdClass;

class CadastraOfertaRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $idCampanhaBrindes;

    /**
     * @var string
     */
    private $idOferta;

    /**
     * @var string
     */
    private $nomeBrinde;

    /**
     * @var string
     */
    private $qtdeBrindes;

    /**
     * @param string $idCampanhaBrindes
     * @param string $idOferta
     * @param string $nomeBrinde
     * @param string $qtdeBrindes
     */
    public function __construct(string $idCampanhaBrindes, string $idOferta, string $nomeBrinde, string $qtdeBrindes)
    {
        $this->idCampanhaBrindes = $idCampanhaBrindes;
        $this->idOferta = $idOferta;
        $this->nomeBrinde = $nomeBrinde;
        $this->qtdeBrindes = $qtdeBrindes;
    }

    /**
     * Returns Id Campanha Brindes.
     */
    public function getIdCampanhaBrindes(): string
    {
        return $this->idCampanhaBrindes;
    }

    /**
     * Sets Id Campanha Brindes.
     *
     * @required
     * @maps id_campanha_brindes
     */
    public function setIdCampanhaBrindes(string $idCampanhaBrindes): void
    {
        $this->idCampanhaBrindes = $idCampanhaBrindes;
    }

    /**
     * Returns Id Oferta.
     */
    public function getIdOferta(): string
    {
        return $this->idOferta;
    }

    /**
     * Sets Id Oferta.
     *
     * @required
     * @maps id_oferta
     */
    public function setIdOferta(string $idOferta): void
    {
        $this->idOferta = $idOferta;
    }

    /**
     * Returns Nome Brinde.
     */
    public function getNomeBrinde(): string
    {
        return $this->nomeBrinde;
    }

    /**
     * Sets Nome Brinde.
     *
     * @required
     * @maps nomeBrinde
     */
    public function setNomeBrinde(string $nomeBrinde): void
    {
        $this->nomeBrinde = $nomeBrinde;
    }

    /**
     * Returns Qtde Brindes.
     */
    public function getQtdeBrindes(): string
    {
        return $this->qtdeBrindes;
    }

    /**
     * Sets Qtde Brindes.
     *
     * @required
     * @maps qtdeBrindes
     */
    public function setQtdeBrindes(string $qtdeBrindes): void
    {
        $this->qtdeBrindes = $qtdeBrindes;
    }

    /**
     * Converts the CadastraOfertaRequest object to a human-readable string representation.
     *
     * @return string The string representation of the CadastraOfertaRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CadastraOfertaRequest',
            [
                'idCampanhaBrindes' => $this->idCampanhaBrindes,
                'idOferta' => $this->idOferta,
                'nomeBrinde' => $this->nomeBrinde,
                'qtdeBrindes' => $this->qtdeBrindes
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['id_campanha_brindes'] = $this->idCampanhaBrindes;
        $json['id_oferta']           = $this->idOferta;
        $json['nomeBrinde']          = $this->nomeBrinde;
        $json['qtdeBrindes']         = $this->qtdeBrindes;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
