<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models;

use ApiB4CLib\ApiHelper;
use stdClass;

class CadastraCampanhaRequest1 implements \JsonSerializable
{
    /**
     * @var string
     */
    private $idCampanhaBrindes;

    /**
     * @var string
     */
    private $nomeCampanhaBrindes;

    /**
     * @var string
     */
    private $inicioCampanhaBrindes;

    /**
     * @var string
     */
    private $fimCampanhaBrindes;

    /**
     * @param string $idCampanhaBrindes
     * @param string $nomeCampanhaBrindes
     * @param string $inicioCampanhaBrindes
     * @param string $fimCampanhaBrindes
     */
    public function __construct(
        string $idCampanhaBrindes,
        string $nomeCampanhaBrindes,
        string $inicioCampanhaBrindes,
        string $fimCampanhaBrindes
    ) {
        $this->idCampanhaBrindes = $idCampanhaBrindes;
        $this->nomeCampanhaBrindes = $nomeCampanhaBrindes;
        $this->inicioCampanhaBrindes = $inicioCampanhaBrindes;
        $this->fimCampanhaBrindes = $fimCampanhaBrindes;
    }

    /**
     * Returns Id Campanha Brindes.
     */
    public function getIdCampanhaBrindes(): string
    {
        return $this->idCampanhaBrindes;
    }

    /**
     * Sets Id Campanha Brindes.
     *
     * @required
     * @maps id_campanha_brindes
     */
    public function setIdCampanhaBrindes(string $idCampanhaBrindes): void
    {
        $this->idCampanhaBrindes = $idCampanhaBrindes;
    }

    /**
     * Returns Nome Campanha Brindes.
     */
    public function getNomeCampanhaBrindes(): string
    {
        return $this->nomeCampanhaBrindes;
    }

    /**
     * Sets Nome Campanha Brindes.
     *
     * @required
     * @maps nome_campanha_brindes
     */
    public function setNomeCampanhaBrindes(string $nomeCampanhaBrindes): void
    {
        $this->nomeCampanhaBrindes = $nomeCampanhaBrindes;
    }

    /**
     * Returns Inicio Campanha Brindes.
     */
    public function getInicioCampanhaBrindes(): string
    {
        return $this->inicioCampanhaBrindes;
    }

    /**
     * Sets Inicio Campanha Brindes.
     *
     * @required
     * @maps inicio_campanha_brindes
     */
    public function setInicioCampanhaBrindes(string $inicioCampanhaBrindes): void
    {
        $this->inicioCampanhaBrindes = $inicioCampanhaBrindes;
    }

    /**
     * Returns Fim Campanha Brindes.
     */
    public function getFimCampanhaBrindes(): string
    {
        return $this->fimCampanhaBrindes;
    }

    /**
     * Sets Fim Campanha Brindes.
     *
     * @required
     * @maps fim_campanha_brindes
     */
    public function setFimCampanhaBrindes(string $fimCampanhaBrindes): void
    {
        $this->fimCampanhaBrindes = $fimCampanhaBrindes;
    }

    /**
     * Converts the CadastraCampanhaRequest1 object to a human-readable string representation.
     *
     * @return string The string representation of the CadastraCampanhaRequest1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CadastraCampanhaRequest1',
            [
                'idCampanhaBrindes' => $this->idCampanhaBrindes,
                'nomeCampanhaBrindes' => $this->nomeCampanhaBrindes,
                'inicioCampanhaBrindes' => $this->inicioCampanhaBrindes,
                'fimCampanhaBrindes' => $this->fimCampanhaBrindes
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['id_campanha_brindes']     = $this->idCampanhaBrindes;
        $json['nome_campanha_brindes']   = $this->nomeCampanhaBrindes;
        $json['inicio_campanha_brindes'] = $this->inicioCampanhaBrindes;
        $json['fim_campanha_brindes']    = $this->fimCampanhaBrindes;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
