<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models;

use ApiB4CLib\ApiHelper;
use stdClass;

class CadastrarAcessorioRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $produtoSku;

    /**
     * @var string
     */
    private $acessorioSku;

    /**
     * @var string
     */
    private $base64;

    /**
     * @param string $produtoSku
     * @param string $acessorioSku
     * @param string $base64
     */
    public function __construct(string $produtoSku, string $acessorioSku, string $base64)
    {
        $this->produtoSku = $produtoSku;
        $this->acessorioSku = $acessorioSku;
        $this->base64 = $base64;
    }

    /**
     * Returns Produto Sku.
     */
    public function getProdutoSku(): string
    {
        return $this->produtoSku;
    }

    /**
     * Sets Produto Sku.
     *
     * @required
     * @maps produto_sku
     */
    public function setProdutoSku(string $produtoSku): void
    {
        $this->produtoSku = $produtoSku;
    }

    /**
     * Returns Acessorio Sku.
     */
    public function getAcessorioSku(): string
    {
        return $this->acessorioSku;
    }

    /**
     * Sets Acessorio Sku.
     *
     * @required
     * @maps acessorio_sku
     */
    public function setAcessorioSku(string $acessorioSku): void
    {
        $this->acessorioSku = $acessorioSku;
    }

    /**
     * Returns Base 64.
     */
    public function getBase64(): string
    {
        return $this->base64;
    }

    /**
     * Sets Base 64.
     *
     * @required
     * @maps base_64
     */
    public function setBase64(string $base64): void
    {
        $this->base64 = $base64;
    }

    /**
     * Converts the CadastrarAcessorioRequest object to a human-readable string representation.
     *
     * @return string The string representation of the CadastrarAcessorioRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CadastrarAcessorioRequest',
            ['produtoSku' => $this->produtoSku, 'acessorioSku' => $this->acessorioSku, 'base64' => $this->base64]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['produto_sku']   = $this->produtoSku;
        $json['acessorio_sku'] = $this->acessorioSku;
        $json['base_64']       = $this->base64;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
