<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models;

use ApiB4CLib\ApiHelper;
use stdClass;

class ConsultaCampanha3 implements \JsonSerializable
{
    /**
     * @var string
     */
    private $idCampanhaBrindes;

    /**
     * @var string
     */
    private $statusCampanhaBrindes;

    /**
     * @var string
     */
    private $nomeCampanhaBrindes;

    /**
     * @var string
     */
    private $tipoCampanhaBrindes;

    /**
     * @var string
     */
    private $inicioCampanhaBrindes;

    /**
     * @var string
     */
    private $fimCampanhaBrindes;

    /**
     * @var string
     */
    private $logoCampanhaBrindes;

    /**
     * @var string|null
     */
    private $bannerCampanhaBrindes;

    /**
     * @var string
     */
    private $obsCampanhaBrindes;

    /**
     * @var string
     */
    private $identificadorCampanhaBrindes;

    /**
     * @var string
     */
    private $priorididadeCampanhaBrindes;

    /**
     * @var string
     */
    private $brindesUtms;

    /**
     * @param string $idCampanhaBrindes
     * @param string $statusCampanhaBrindes
     * @param string $nomeCampanhaBrindes
     * @param string $tipoCampanhaBrindes
     * @param string $inicioCampanhaBrindes
     * @param string $fimCampanhaBrindes
     * @param string $logoCampanhaBrindes
     * @param string $obsCampanhaBrindes
     * @param string $identificadorCampanhaBrindes
     * @param string $priorididadeCampanhaBrindes
     * @param string $brindesUtms
     */
    public function __construct(
        string $idCampanhaBrindes,
        string $statusCampanhaBrindes,
        string $nomeCampanhaBrindes,
        string $tipoCampanhaBrindes,
        string $inicioCampanhaBrindes,
        string $fimCampanhaBrindes,
        string $logoCampanhaBrindes,
        string $obsCampanhaBrindes,
        string $identificadorCampanhaBrindes,
        string $priorididadeCampanhaBrindes,
        string $brindesUtms
    ) {
        $this->idCampanhaBrindes = $idCampanhaBrindes;
        $this->statusCampanhaBrindes = $statusCampanhaBrindes;
        $this->nomeCampanhaBrindes = $nomeCampanhaBrindes;
        $this->tipoCampanhaBrindes = $tipoCampanhaBrindes;
        $this->inicioCampanhaBrindes = $inicioCampanhaBrindes;
        $this->fimCampanhaBrindes = $fimCampanhaBrindes;
        $this->logoCampanhaBrindes = $logoCampanhaBrindes;
        $this->obsCampanhaBrindes = $obsCampanhaBrindes;
        $this->identificadorCampanhaBrindes = $identificadorCampanhaBrindes;
        $this->priorididadeCampanhaBrindes = $priorididadeCampanhaBrindes;
        $this->brindesUtms = $brindesUtms;
    }

    /**
     * Returns Id Campanha Brindes.
     */
    public function getIdCampanhaBrindes(): string
    {
        return $this->idCampanhaBrindes;
    }

    /**
     * Sets Id Campanha Brindes.
     *
     * @required
     * @maps id_campanha_brindes
     */
    public function setIdCampanhaBrindes(string $idCampanhaBrindes): void
    {
        $this->idCampanhaBrindes = $idCampanhaBrindes;
    }

    /**
     * Returns Status Campanha Brindes.
     */
    public function getStatusCampanhaBrindes(): string
    {
        return $this->statusCampanhaBrindes;
    }

    /**
     * Sets Status Campanha Brindes.
     *
     * @required
     * @maps status_campanha_brindes
     */
    public function setStatusCampanhaBrindes(string $statusCampanhaBrindes): void
    {
        $this->statusCampanhaBrindes = $statusCampanhaBrindes;
    }

    /**
     * Returns Nome Campanha Brindes.
     */
    public function getNomeCampanhaBrindes(): string
    {
        return $this->nomeCampanhaBrindes;
    }

    /**
     * Sets Nome Campanha Brindes.
     *
     * @required
     * @maps nome_campanha_brindes
     */
    public function setNomeCampanhaBrindes(string $nomeCampanhaBrindes): void
    {
        $this->nomeCampanhaBrindes = $nomeCampanhaBrindes;
    }

    /**
     * Returns Tipo Campanha Brindes.
     */
    public function getTipoCampanhaBrindes(): string
    {
        return $this->tipoCampanhaBrindes;
    }

    /**
     * Sets Tipo Campanha Brindes.
     *
     * @required
     * @maps tipo_campanha_brindes
     */
    public function setTipoCampanhaBrindes(string $tipoCampanhaBrindes): void
    {
        $this->tipoCampanhaBrindes = $tipoCampanhaBrindes;
    }

    /**
     * Returns Inicio Campanha Brindes.
     */
    public function getInicioCampanhaBrindes(): string
    {
        return $this->inicioCampanhaBrindes;
    }

    /**
     * Sets Inicio Campanha Brindes.
     *
     * @required
     * @maps inicio_campanha_brindes
     */
    public function setInicioCampanhaBrindes(string $inicioCampanhaBrindes): void
    {
        $this->inicioCampanhaBrindes = $inicioCampanhaBrindes;
    }

    /**
     * Returns Fim Campanha Brindes.
     */
    public function getFimCampanhaBrindes(): string
    {
        return $this->fimCampanhaBrindes;
    }

    /**
     * Sets Fim Campanha Brindes.
     *
     * @required
     * @maps fim_campanha_brindes
     */
    public function setFimCampanhaBrindes(string $fimCampanhaBrindes): void
    {
        $this->fimCampanhaBrindes = $fimCampanhaBrindes;
    }

    /**
     * Returns Logo Campanha Brindes.
     */
    public function getLogoCampanhaBrindes(): string
    {
        return $this->logoCampanhaBrindes;
    }

    /**
     * Sets Logo Campanha Brindes.
     *
     * @required
     * @maps logo_campanha_brindes
     */
    public function setLogoCampanhaBrindes(string $logoCampanhaBrindes): void
    {
        $this->logoCampanhaBrindes = $logoCampanhaBrindes;
    }

    /**
     * Returns Banner Campanha Brindes.
     */
    public function getBannerCampanhaBrindes(): ?string
    {
        return $this->bannerCampanhaBrindes;
    }

    /**
     * Sets Banner Campanha Brindes.
     *
     * @maps banner_campanha_brindes
     */
    public function setBannerCampanhaBrindes(?string $bannerCampanhaBrindes): void
    {
        $this->bannerCampanhaBrindes = $bannerCampanhaBrindes;
    }

    /**
     * Returns Obs Campanha Brindes.
     */
    public function getObsCampanhaBrindes(): string
    {
        return $this->obsCampanhaBrindes;
    }

    /**
     * Sets Obs Campanha Brindes.
     *
     * @required
     * @maps obs_campanha_brindes
     */
    public function setObsCampanhaBrindes(string $obsCampanhaBrindes): void
    {
        $this->obsCampanhaBrindes = $obsCampanhaBrindes;
    }

    /**
     * Returns Identificador Campanha Brindes.
     */
    public function getIdentificadorCampanhaBrindes(): string
    {
        return $this->identificadorCampanhaBrindes;
    }

    /**
     * Sets Identificador Campanha Brindes.
     *
     * @required
     * @maps identificador_campanha_brindes
     */
    public function setIdentificadorCampanhaBrindes(string $identificadorCampanhaBrindes): void
    {
        $this->identificadorCampanhaBrindes = $identificadorCampanhaBrindes;
    }

    /**
     * Returns Priorididade Campanha Brindes.
     */
    public function getPriorididadeCampanhaBrindes(): string
    {
        return $this->priorididadeCampanhaBrindes;
    }

    /**
     * Sets Priorididade Campanha Brindes.
     *
     * @required
     * @maps priorididade_campanha_brindes
     */
    public function setPriorididadeCampanhaBrindes(string $priorididadeCampanhaBrindes): void
    {
        $this->priorididadeCampanhaBrindes = $priorididadeCampanhaBrindes;
    }

    /**
     * Returns Brindes Utms.
     */
    public function getBrindesUtms(): string
    {
        return $this->brindesUtms;
    }

    /**
     * Sets Brindes Utms.
     *
     * @required
     * @maps brindes_utms
     */
    public function setBrindesUtms(string $brindesUtms): void
    {
        $this->brindesUtms = $brindesUtms;
    }

    /**
     * Converts the ConsultaCampanha3 object to a human-readable string representation.
     *
     * @return string The string representation of the ConsultaCampanha3 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ConsultaCampanha3',
            [
                'idCampanhaBrindes' => $this->idCampanhaBrindes,
                'statusCampanhaBrindes' => $this->statusCampanhaBrindes,
                'nomeCampanhaBrindes' => $this->nomeCampanhaBrindes,
                'tipoCampanhaBrindes' => $this->tipoCampanhaBrindes,
                'inicioCampanhaBrindes' => $this->inicioCampanhaBrindes,
                'fimCampanhaBrindes' => $this->fimCampanhaBrindes,
                'logoCampanhaBrindes' => $this->logoCampanhaBrindes,
                'bannerCampanhaBrindes' => $this->bannerCampanhaBrindes,
                'obsCampanhaBrindes' => $this->obsCampanhaBrindes,
                'identificadorCampanhaBrindes' => $this->identificadorCampanhaBrindes,
                'priorididadeCampanhaBrindes' => $this->priorididadeCampanhaBrindes,
                'brindesUtms' => $this->brindesUtms
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['id_campanha_brindes']            = $this->idCampanhaBrindes;
        $json['status_campanha_brindes']        = $this->statusCampanhaBrindes;
        $json['nome_campanha_brindes']          = $this->nomeCampanhaBrindes;
        $json['tipo_campanha_brindes']          = $this->tipoCampanhaBrindes;
        $json['inicio_campanha_brindes']        = $this->inicioCampanhaBrindes;
        $json['fim_campanha_brindes']           = $this->fimCampanhaBrindes;
        $json['logo_campanha_brindes']          = $this->logoCampanhaBrindes;
        $json['banner_campanha_brindes']        = $this->bannerCampanhaBrindes;
        $json['obs_campanha_brindes']           = $this->obsCampanhaBrindes;
        $json['identificador_campanha_brindes'] = $this->identificadorCampanhaBrindes;
        $json['priorididade_campanha_brindes']  = $this->priorididadeCampanhaBrindes;
        $json['brindes_utms']                   = $this->brindesUtms;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
