<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models;

use ApiB4CLib\ApiHelper;
use stdClass;

class ConsultaFilial implements \JsonSerializable
{
    /**
     * @var string
     */
    private $codigo;

    /**
     * @var string
     */
    private $nome;

    /**
     * @var string
     */
    private $razaoSocial;

    /**
     * @var string
     */
    private $cnpj;

    /**
     * @var string
     */
    private $cep;

    /**
     * @var string
     */
    private $endereco;

    /**
     * @var string
     */
    private $numero;

    /**
     * @var string
     */
    private $complemento;

    /**
     * @var string
     */
    private $bairro;

    /**
     * @var string
     */
    private $cidade;

    /**
     * @var string
     */
    private $uf;

    /**
     * @var string
     */
    private $fone;

    /**
     * @var string
     */
    private $fone2;

    /**
     * @var string
     */
    private $urlGoogleMaps;

    /**
     * @var string
     */
    private $urlVideoYoutube;

    /**
     * @var string
     */
    private $possuiEstacionamento;

    /**
     * @var string
     */
    private $horarioAtendimento;

    /**
     * @var string
     */
    private $status;

    /**
     * @param string $codigo
     * @param string $nome
     * @param string $razaoSocial
     * @param string $cnpj
     * @param string $cep
     * @param string $endereco
     * @param string $numero
     * @param string $complemento
     * @param string $bairro
     * @param string $cidade
     * @param string $uf
     * @param string $fone
     * @param string $fone2
     * @param string $urlGoogleMaps
     * @param string $urlVideoYoutube
     * @param string $possuiEstacionamento
     * @param string $horarioAtendimento
     * @param string $status
     */
    public function __construct(
        string $codigo,
        string $nome,
        string $razaoSocial,
        string $cnpj,
        string $cep,
        string $endereco,
        string $numero,
        string $complemento,
        string $bairro,
        string $cidade,
        string $uf,
        string $fone,
        string $fone2,
        string $urlGoogleMaps,
        string $urlVideoYoutube,
        string $possuiEstacionamento,
        string $horarioAtendimento,
        string $status
    ) {
        $this->codigo = $codigo;
        $this->nome = $nome;
        $this->razaoSocial = $razaoSocial;
        $this->cnpj = $cnpj;
        $this->cep = $cep;
        $this->endereco = $endereco;
        $this->numero = $numero;
        $this->complemento = $complemento;
        $this->bairro = $bairro;
        $this->cidade = $cidade;
        $this->uf = $uf;
        $this->fone = $fone;
        $this->fone2 = $fone2;
        $this->urlGoogleMaps = $urlGoogleMaps;
        $this->urlVideoYoutube = $urlVideoYoutube;
        $this->possuiEstacionamento = $possuiEstacionamento;
        $this->horarioAtendimento = $horarioAtendimento;
        $this->status = $status;
    }

    /**
     * Returns Codigo.
     */
    public function getCodigo(): string
    {
        return $this->codigo;
    }

    /**
     * Sets Codigo.
     *
     * @required
     * @maps codigo
     */
    public function setCodigo(string $codigo): void
    {
        $this->codigo = $codigo;
    }

    /**
     * Returns Nome.
     */
    public function getNome(): string
    {
        return $this->nome;
    }

    /**
     * Sets Nome.
     *
     * @required
     * @maps nome
     */
    public function setNome(string $nome): void
    {
        $this->nome = $nome;
    }

    /**
     * Returns Razao Social.
     */
    public function getRazaoSocial(): string
    {
        return $this->razaoSocial;
    }

    /**
     * Sets Razao Social.
     *
     * @required
     * @maps razao_social
     */
    public function setRazaoSocial(string $razaoSocial): void
    {
        $this->razaoSocial = $razaoSocial;
    }

    /**
     * Returns Cnpj.
     */
    public function getCnpj(): string
    {
        return $this->cnpj;
    }

    /**
     * Sets Cnpj.
     *
     * @required
     * @maps cnpj
     */
    public function setCnpj(string $cnpj): void
    {
        $this->cnpj = $cnpj;
    }

    /**
     * Returns Cep.
     */
    public function getCep(): string
    {
        return $this->cep;
    }

    /**
     * Sets Cep.
     *
     * @required
     * @maps cep
     */
    public function setCep(string $cep): void
    {
        $this->cep = $cep;
    }

    /**
     * Returns Endereco.
     */
    public function getEndereco(): string
    {
        return $this->endereco;
    }

    /**
     * Sets Endereco.
     *
     * @required
     * @maps endereco
     */
    public function setEndereco(string $endereco): void
    {
        $this->endereco = $endereco;
    }

    /**
     * Returns Numero.
     */
    public function getNumero(): string
    {
        return $this->numero;
    }

    /**
     * Sets Numero.
     *
     * @required
     * @maps numero
     */
    public function setNumero(string $numero): void
    {
        $this->numero = $numero;
    }

    /**
     * Returns Complemento.
     */
    public function getComplemento(): string
    {
        return $this->complemento;
    }

    /**
     * Sets Complemento.
     *
     * @required
     * @maps complemento
     */
    public function setComplemento(string $complemento): void
    {
        $this->complemento = $complemento;
    }

    /**
     * Returns Bairro.
     */
    public function getBairro(): string
    {
        return $this->bairro;
    }

    /**
     * Sets Bairro.
     *
     * @required
     * @maps bairro
     */
    public function setBairro(string $bairro): void
    {
        $this->bairro = $bairro;
    }

    /**
     * Returns Cidade.
     */
    public function getCidade(): string
    {
        return $this->cidade;
    }

    /**
     * Sets Cidade.
     *
     * @required
     * @maps cidade
     */
    public function setCidade(string $cidade): void
    {
        $this->cidade = $cidade;
    }

    /**
     * Returns Uf.
     */
    public function getUf(): string
    {
        return $this->uf;
    }

    /**
     * Sets Uf.
     *
     * @required
     * @maps uf
     */
    public function setUf(string $uf): void
    {
        $this->uf = $uf;
    }

    /**
     * Returns Fone.
     */
    public function getFone(): string
    {
        return $this->fone;
    }

    /**
     * Sets Fone.
     *
     * @required
     * @maps fone
     */
    public function setFone(string $fone): void
    {
        $this->fone = $fone;
    }

    /**
     * Returns Fone 2.
     */
    public function getFone2(): string
    {
        return $this->fone2;
    }

    /**
     * Sets Fone 2.
     *
     * @required
     * @maps fone2
     */
    public function setFone2(string $fone2): void
    {
        $this->fone2 = $fone2;
    }

    /**
     * Returns Url Google Maps.
     */
    public function getUrlGoogleMaps(): string
    {
        return $this->urlGoogleMaps;
    }

    /**
     * Sets Url Google Maps.
     *
     * @required
     * @maps url_google_maps
     */
    public function setUrlGoogleMaps(string $urlGoogleMaps): void
    {
        $this->urlGoogleMaps = $urlGoogleMaps;
    }

    /**
     * Returns Url Video Youtube.
     */
    public function getUrlVideoYoutube(): string
    {
        return $this->urlVideoYoutube;
    }

    /**
     * Sets Url Video Youtube.
     *
     * @required
     * @maps url_video_youtube
     */
    public function setUrlVideoYoutube(string $urlVideoYoutube): void
    {
        $this->urlVideoYoutube = $urlVideoYoutube;
    }

    /**
     * Returns Possui Estacionamento.
     */
    public function getPossuiEstacionamento(): string
    {
        return $this->possuiEstacionamento;
    }

    /**
     * Sets Possui Estacionamento.
     *
     * @required
     * @maps possui_estacionamento
     */
    public function setPossuiEstacionamento(string $possuiEstacionamento): void
    {
        $this->possuiEstacionamento = $possuiEstacionamento;
    }

    /**
     * Returns Horario Atendimento.
     */
    public function getHorarioAtendimento(): string
    {
        return $this->horarioAtendimento;
    }

    /**
     * Sets Horario Atendimento.
     *
     * @required
     * @maps horario_atendimento
     */
    public function setHorarioAtendimento(string $horarioAtendimento): void
    {
        $this->horarioAtendimento = $horarioAtendimento;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @required
     * @maps status
     */
    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    /**
     * Converts the ConsultaFilial object to a human-readable string representation.
     *
     * @return string The string representation of the ConsultaFilial object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ConsultaFilial',
            [
                'codigo' => $this->codigo,
                'nome' => $this->nome,
                'razaoSocial' => $this->razaoSocial,
                'cnpj' => $this->cnpj,
                'cep' => $this->cep,
                'endereco' => $this->endereco,
                'numero' => $this->numero,
                'complemento' => $this->complemento,
                'bairro' => $this->bairro,
                'cidade' => $this->cidade,
                'uf' => $this->uf,
                'fone' => $this->fone,
                'fone2' => $this->fone2,
                'urlGoogleMaps' => $this->urlGoogleMaps,
                'urlVideoYoutube' => $this->urlVideoYoutube,
                'possuiEstacionamento' => $this->possuiEstacionamento,
                'horarioAtendimento' => $this->horarioAtendimento,
                'status' => $this->status
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['codigo']                = $this->codigo;
        $json['nome']                  = $this->nome;
        $json['razao_social']          = $this->razaoSocial;
        $json['cnpj']                  = $this->cnpj;
        $json['cep']                   = $this->cep;
        $json['endereco']              = $this->endereco;
        $json['numero']                = $this->numero;
        $json['complemento']           = $this->complemento;
        $json['bairro']                = $this->bairro;
        $json['cidade']                = $this->cidade;
        $json['uf']                    = $this->uf;
        $json['fone']                  = $this->fone;
        $json['fone2']                 = $this->fone2;
        $json['url_google_maps']       = $this->urlGoogleMaps;
        $json['url_video_youtube']     = $this->urlVideoYoutube;
        $json['possui_estacionamento'] = $this->possuiEstacionamento;
        $json['horario_atendimento']   = $this->horarioAtendimento;
        $json['status']                = $this->status;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
