<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models;

use ApiB4CLib\ApiHelper;
use stdClass;

class ConsultaProdutos1 implements \JsonSerializable
{
    /**
     * @var string
     */
    private $idCampanhaLevemais;

    /**
     * @var string
     */
    private $statusCampanhaLevemais;

    /**
     * @var string
     */
    private $nomeCampanhaLevemais;

    /**
     * @var string
     */
    private $inicioCampanhaLevemais;

    /**
     * @var string
     */
    private $fimCampanhaLevemais;

    /**
     * @var string
     */
    private $prioridadeCampanhaLevemais;

    /**
     * @var string
     */
    private $comprandoProdutos;

    /**
     * @var string
     */
    private $numeroProdutosBeneficio;

    /**
     * @var string
     */
    private $percentualDesconto;

    /**
     * @var string
     */
    private $produtosLevemais;

    /**
     * @param string $idCampanhaLevemais
     * @param string $statusCampanhaLevemais
     * @param string $nomeCampanhaLevemais
     * @param string $inicioCampanhaLevemais
     * @param string $fimCampanhaLevemais
     * @param string $prioridadeCampanhaLevemais
     * @param string $comprandoProdutos
     * @param string $numeroProdutosBeneficio
     * @param string $percentualDesconto
     * @param string $produtosLevemais
     */
    public function __construct(
        string $idCampanhaLevemais,
        string $statusCampanhaLevemais,
        string $nomeCampanhaLevemais,
        string $inicioCampanhaLevemais,
        string $fimCampanhaLevemais,
        string $prioridadeCampanhaLevemais,
        string $comprandoProdutos,
        string $numeroProdutosBeneficio,
        string $percentualDesconto,
        string $produtosLevemais
    ) {
        $this->idCampanhaLevemais = $idCampanhaLevemais;
        $this->statusCampanhaLevemais = $statusCampanhaLevemais;
        $this->nomeCampanhaLevemais = $nomeCampanhaLevemais;
        $this->inicioCampanhaLevemais = $inicioCampanhaLevemais;
        $this->fimCampanhaLevemais = $fimCampanhaLevemais;
        $this->prioridadeCampanhaLevemais = $prioridadeCampanhaLevemais;
        $this->comprandoProdutos = $comprandoProdutos;
        $this->numeroProdutosBeneficio = $numeroProdutosBeneficio;
        $this->percentualDesconto = $percentualDesconto;
        $this->produtosLevemais = $produtosLevemais;
    }

    /**
     * Returns Id Campanha Levemais.
     */
    public function getIdCampanhaLevemais(): string
    {
        return $this->idCampanhaLevemais;
    }

    /**
     * Sets Id Campanha Levemais.
     *
     * @required
     * @maps id_campanha_levemais
     */
    public function setIdCampanhaLevemais(string $idCampanhaLevemais): void
    {
        $this->idCampanhaLevemais = $idCampanhaLevemais;
    }

    /**
     * Returns Status Campanha Levemais.
     */
    public function getStatusCampanhaLevemais(): string
    {
        return $this->statusCampanhaLevemais;
    }

    /**
     * Sets Status Campanha Levemais.
     *
     * @required
     * @maps status_campanha_levemais
     */
    public function setStatusCampanhaLevemais(string $statusCampanhaLevemais): void
    {
        $this->statusCampanhaLevemais = $statusCampanhaLevemais;
    }

    /**
     * Returns Nome Campanha Levemais.
     */
    public function getNomeCampanhaLevemais(): string
    {
        return $this->nomeCampanhaLevemais;
    }

    /**
     * Sets Nome Campanha Levemais.
     *
     * @required
     * @maps nome_campanha_levemais
     */
    public function setNomeCampanhaLevemais(string $nomeCampanhaLevemais): void
    {
        $this->nomeCampanhaLevemais = $nomeCampanhaLevemais;
    }

    /**
     * Returns Inicio Campanha Levemais.
     */
    public function getInicioCampanhaLevemais(): string
    {
        return $this->inicioCampanhaLevemais;
    }

    /**
     * Sets Inicio Campanha Levemais.
     *
     * @required
     * @maps inicio_campanha_levemais
     */
    public function setInicioCampanhaLevemais(string $inicioCampanhaLevemais): void
    {
        $this->inicioCampanhaLevemais = $inicioCampanhaLevemais;
    }

    /**
     * Returns Fim Campanha Levemais.
     */
    public function getFimCampanhaLevemais(): string
    {
        return $this->fimCampanhaLevemais;
    }

    /**
     * Sets Fim Campanha Levemais.
     *
     * @required
     * @maps fim_campanha_levemais
     */
    public function setFimCampanhaLevemais(string $fimCampanhaLevemais): void
    {
        $this->fimCampanhaLevemais = $fimCampanhaLevemais;
    }

    /**
     * Returns Prioridade Campanha Levemais.
     */
    public function getPrioridadeCampanhaLevemais(): string
    {
        return $this->prioridadeCampanhaLevemais;
    }

    /**
     * Sets Prioridade Campanha Levemais.
     *
     * @required
     * @maps prioridade_campanha_levemais
     */
    public function setPrioridadeCampanhaLevemais(string $prioridadeCampanhaLevemais): void
    {
        $this->prioridadeCampanhaLevemais = $prioridadeCampanhaLevemais;
    }

    /**
     * Returns Comprando Produtos.
     */
    public function getComprandoProdutos(): string
    {
        return $this->comprandoProdutos;
    }

    /**
     * Sets Comprando Produtos.
     *
     * @required
     * @maps comprando_produtos
     */
    public function setComprandoProdutos(string $comprandoProdutos): void
    {
        $this->comprandoProdutos = $comprandoProdutos;
    }

    /**
     * Returns Numero Produtos Beneficio.
     */
    public function getNumeroProdutosBeneficio(): string
    {
        return $this->numeroProdutosBeneficio;
    }

    /**
     * Sets Numero Produtos Beneficio.
     *
     * @required
     * @maps numero_produtos_beneficio
     */
    public function setNumeroProdutosBeneficio(string $numeroProdutosBeneficio): void
    {
        $this->numeroProdutosBeneficio = $numeroProdutosBeneficio;
    }

    /**
     * Returns Percentual Desconto.
     */
    public function getPercentualDesconto(): string
    {
        return $this->percentualDesconto;
    }

    /**
     * Sets Percentual Desconto.
     *
     * @required
     * @maps percentual_desconto
     */
    public function setPercentualDesconto(string $percentualDesconto): void
    {
        $this->percentualDesconto = $percentualDesconto;
    }

    /**
     * Returns Produtos Levemais.
     */
    public function getProdutosLevemais(): string
    {
        return $this->produtosLevemais;
    }

    /**
     * Sets Produtos Levemais.
     *
     * @required
     * @maps produtos_levemais
     */
    public function setProdutosLevemais(string $produtosLevemais): void
    {
        $this->produtosLevemais = $produtosLevemais;
    }

    /**
     * Converts the ConsultaProdutos1 object to a human-readable string representation.
     *
     * @return string The string representation of the ConsultaProdutos1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ConsultaProdutos1',
            [
                'idCampanhaLevemais' => $this->idCampanhaLevemais,
                'statusCampanhaLevemais' => $this->statusCampanhaLevemais,
                'nomeCampanhaLevemais' => $this->nomeCampanhaLevemais,
                'inicioCampanhaLevemais' => $this->inicioCampanhaLevemais,
                'fimCampanhaLevemais' => $this->fimCampanhaLevemais,
                'prioridadeCampanhaLevemais' => $this->prioridadeCampanhaLevemais,
                'comprandoProdutos' => $this->comprandoProdutos,
                'numeroProdutosBeneficio' => $this->numeroProdutosBeneficio,
                'percentualDesconto' => $this->percentualDesconto,
                'produtosLevemais' => $this->produtosLevemais
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['id_campanha_levemais']         = $this->idCampanhaLevemais;
        $json['status_campanha_levemais']     = $this->statusCampanhaLevemais;
        $json['nome_campanha_levemais']       = $this->nomeCampanhaLevemais;
        $json['inicio_campanha_levemais']     = $this->inicioCampanhaLevemais;
        $json['fim_campanha_levemais']        = $this->fimCampanhaLevemais;
        $json['prioridade_campanha_levemais'] = $this->prioridadeCampanhaLevemais;
        $json['comprando_produtos']           = $this->comprandoProdutos;
        $json['numero_produtos_beneficio']    = $this->numeroProdutosBeneficio;
        $json['percentual_desconto']          = $this->percentualDesconto;
        $json['produtos_levemais']            = $this->produtosLevemais;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
