<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models;

use ApiB4CLib\ApiHelper;
use stdClass;

class ConsultaQuantidade implements \JsonSerializable
{
    /**
     * @var Campanha
     */
    private $campanha;

    /**
     * @var Brindes2[]
     */
    private $brindes;

    /**
     * @param Campanha $campanha
     * @param Brindes2[] $brindes
     */
    public function __construct(Campanha $campanha, array $brindes)
    {
        $this->campanha = $campanha;
        $this->brindes = $brindes;
    }

    /**
     * Returns Campanha.
     */
    public function getCampanha(): Campanha
    {
        return $this->campanha;
    }

    /**
     * Sets Campanha.
     *
     * @required
     * @maps campanha
     */
    public function setCampanha(Campanha $campanha): void
    {
        $this->campanha = $campanha;
    }

    /**
     * Returns Brindes.
     *
     * @return Brindes2[]
     */
    public function getBrindes(): array
    {
        return $this->brindes;
    }

    /**
     * Sets Brindes.
     *
     * @required
     * @maps brindes
     *
     * @param Brindes2[] $brindes
     */
    public function setBrindes(array $brindes): void
    {
        $this->brindes = $brindes;
    }

    /**
     * Converts the ConsultaQuantidade object to a human-readable string representation.
     *
     * @return string The string representation of the ConsultaQuantidade object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ConsultaQuantidade',
            ['campanha' => $this->campanha, 'brindes' => $this->brindes]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['campanha'] = $this->campanha;
        $json['brindes']  = $this->brindes;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
