<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models;

use ApiB4CLib\ApiHelper;
use stdClass;

class ConsultaOferta implements \JsonSerializable
{
    /**
     * @var string
     */
    private $idOferta;

    /**
     * @var string
     */
    private $campanhaBrindes;

    /**
     * @var string
     */
    private $statusBrindesOferta;

    /**
     * @var string
     */
    private $valorTotal;

    /**
     * @var string
     */
    private $qtdeBrindes;

    /**
     * @var string
     */
    private $tipoValor;

    /**
     * @var string
     */
    private $nomeBrinde;

    /**
     * @var string
     */
    private $quantidadeTotalCarrinho;

    /**
     * @var string
     */
    private $valorTotalCarrinho;

    /**
     * @param string $idOferta
     * @param string $campanhaBrindes
     * @param string $statusBrindesOferta
     * @param string $valorTotal
     * @param string $qtdeBrindes
     * @param string $tipoValor
     * @param string $nomeBrinde
     * @param string $quantidadeTotalCarrinho
     * @param string $valorTotalCarrinho
     */
    public function __construct(
        string $idOferta,
        string $campanhaBrindes,
        string $statusBrindesOferta,
        string $valorTotal,
        string $qtdeBrindes,
        string $tipoValor,
        string $nomeBrinde,
        string $quantidadeTotalCarrinho,
        string $valorTotalCarrinho
    ) {
        $this->idOferta = $idOferta;
        $this->campanhaBrindes = $campanhaBrindes;
        $this->statusBrindesOferta = $statusBrindesOferta;
        $this->valorTotal = $valorTotal;
        $this->qtdeBrindes = $qtdeBrindes;
        $this->tipoValor = $tipoValor;
        $this->nomeBrinde = $nomeBrinde;
        $this->quantidadeTotalCarrinho = $quantidadeTotalCarrinho;
        $this->valorTotalCarrinho = $valorTotalCarrinho;
    }

    /**
     * Returns Id Oferta.
     */
    public function getIdOferta(): string
    {
        return $this->idOferta;
    }

    /**
     * Sets Id Oferta.
     *
     * @required
     * @maps id_oferta
     */
    public function setIdOferta(string $idOferta): void
    {
        $this->idOferta = $idOferta;
    }

    /**
     * Returns Campanha Brindes.
     */
    public function getCampanhaBrindes(): string
    {
        return $this->campanhaBrindes;
    }

    /**
     * Sets Campanha Brindes.
     *
     * @required
     * @maps campanha_brindes
     */
    public function setCampanhaBrindes(string $campanhaBrindes): void
    {
        $this->campanhaBrindes = $campanhaBrindes;
    }

    /**
     * Returns Status Brindes Oferta.
     */
    public function getStatusBrindesOferta(): string
    {
        return $this->statusBrindesOferta;
    }

    /**
     * Sets Status Brindes Oferta.
     *
     * @required
     * @maps status_brindes_oferta
     */
    public function setStatusBrindesOferta(string $statusBrindesOferta): void
    {
        $this->statusBrindesOferta = $statusBrindesOferta;
    }

    /**
     * Returns Valor Total.
     */
    public function getValorTotal(): string
    {
        return $this->valorTotal;
    }

    /**
     * Sets Valor Total.
     *
     * @required
     * @maps valorTotal
     */
    public function setValorTotal(string $valorTotal): void
    {
        $this->valorTotal = $valorTotal;
    }

    /**
     * Returns Qtde Brindes.
     */
    public function getQtdeBrindes(): string
    {
        return $this->qtdeBrindes;
    }

    /**
     * Sets Qtde Brindes.
     *
     * @required
     * @maps qtdeBrindes
     */
    public function setQtdeBrindes(string $qtdeBrindes): void
    {
        $this->qtdeBrindes = $qtdeBrindes;
    }

    /**
     * Returns Tipo Valor.
     */
    public function getTipoValor(): string
    {
        return $this->tipoValor;
    }

    /**
     * Sets Tipo Valor.
     *
     * @required
     * @maps tipoValor
     */
    public function setTipoValor(string $tipoValor): void
    {
        $this->tipoValor = $tipoValor;
    }

    /**
     * Returns Nome Brinde.
     */
    public function getNomeBrinde(): string
    {
        return $this->nomeBrinde;
    }

    /**
     * Sets Nome Brinde.
     *
     * @required
     * @maps nomeBrinde
     */
    public function setNomeBrinde(string $nomeBrinde): void
    {
        $this->nomeBrinde = $nomeBrinde;
    }

    /**
     * Returns Quantidade Total Carrinho.
     */
    public function getQuantidadeTotalCarrinho(): string
    {
        return $this->quantidadeTotalCarrinho;
    }

    /**
     * Sets Quantidade Total Carrinho.
     *
     * @required
     * @maps quantidade_total_carrinho
     */
    public function setQuantidadeTotalCarrinho(string $quantidadeTotalCarrinho): void
    {
        $this->quantidadeTotalCarrinho = $quantidadeTotalCarrinho;
    }

    /**
     * Returns Valor Total Carrinho.
     */
    public function getValorTotalCarrinho(): string
    {
        return $this->valorTotalCarrinho;
    }

    /**
     * Sets Valor Total Carrinho.
     *
     * @required
     * @maps valor_total_carrinho
     */
    public function setValorTotalCarrinho(string $valorTotalCarrinho): void
    {
        $this->valorTotalCarrinho = $valorTotalCarrinho;
    }

    /**
     * Converts the ConsultaOferta object to a human-readable string representation.
     *
     * @return string The string representation of the ConsultaOferta object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ConsultaOferta',
            [
                'idOferta' => $this->idOferta,
                'campanhaBrindes' => $this->campanhaBrindes,
                'statusBrindesOferta' => $this->statusBrindesOferta,
                'valorTotal' => $this->valorTotal,
                'qtdeBrindes' => $this->qtdeBrindes,
                'tipoValor' => $this->tipoValor,
                'nomeBrinde' => $this->nomeBrinde,
                'quantidadeTotalCarrinho' => $this->quantidadeTotalCarrinho,
                'valorTotalCarrinho' => $this->valorTotalCarrinho
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['id_oferta']                 = $this->idOferta;
        $json['campanha_brindes']          = $this->campanhaBrindes;
        $json['status_brindes_oferta']     = $this->statusBrindesOferta;
        $json['valorTotal']                = $this->valorTotal;
        $json['qtdeBrindes']               = $this->qtdeBrindes;
        $json['tipoValor']                 = $this->tipoValor;
        $json['nomeBrinde']                = $this->nomeBrinde;
        $json['quantidade_total_carrinho'] = $this->quantidadeTotalCarrinho;
        $json['valor_total_carrinho']      = $this->valorTotalCarrinho;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
