<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models;

use ApiB4CLib\ApiHelper;
use stdClass;

class ConsultarNFPedido implements \JsonSerializable
{
    /**
     * @var NotasFiscai[]
     */
    private $notasFiscais;

    /**
     * @param NotasFiscai[] $notasFiscais
     */
    public function __construct(array $notasFiscais)
    {
        $this->notasFiscais = $notasFiscais;
    }

    /**
     * Returns Notas Fiscais.
     *
     * @return NotasFiscai[]
     */
    public function getNotasFiscais(): array
    {
        return $this->notasFiscais;
    }

    /**
     * Sets Notas Fiscais.
     *
     * @required
     * @maps notas_fiscais
     *
     * @param NotasFiscai[] $notasFiscais
     */
    public function setNotasFiscais(array $notasFiscais): void
    {
        $this->notasFiscais = $notasFiscais;
    }

    /**
     * Converts the ConsultarNFPedido object to a human-readable string representation.
     *
     * @return string The string representation of the ConsultarNFPedido object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('ConsultarNFPedido', ['notasFiscais' => $this->notasFiscais]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['notas_fiscais'] = $this->notasFiscais;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
