<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models;

use ApiB4CLib\ApiHelper;
use stdClass;

class DeletarProdutosRequest1 implements \JsonSerializable
{
    /**
     * @var string[]
     */
    private $produtos;

    /**
     * @param string[] $produtos
     */
    public function __construct(array $produtos)
    {
        $this->produtos = $produtos;
    }

    /**
     * Returns Produtos.
     *
     * @return string[]
     */
    public function getProdutos(): array
    {
        return $this->produtos;
    }

    /**
     * Sets Produtos.
     *
     * @required
     * @maps produtos
     *
     * @param string[] $produtos
     */
    public function setProdutos(array $produtos): void
    {
        $this->produtos = $produtos;
    }

    /**
     * Converts the DeletarProdutosRequest1 object to a human-readable string representation.
     *
     * @return string The string representation of the DeletarProdutosRequest1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('DeletarProdutosRequest1', ['produtos' => $this->produtos]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['produtos'] = $this->produtos;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
