<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models;

use ApiB4CLib\ApiHelper;
use stdClass;

class DeletarPrecoRequest implements \JsonSerializable
{
    /**
     * @var int
     */
    private $idCampanhaPromocional;

    /**
     * @param int $idCampanhaPromocional
     */
    public function __construct(int $idCampanhaPromocional)
    {
        $this->idCampanhaPromocional = $idCampanhaPromocional;
    }

    /**
     * Returns Id Campanha Promocional.
     */
    public function getIdCampanhaPromocional(): int
    {
        return $this->idCampanhaPromocional;
    }

    /**
     * Sets Id Campanha Promocional.
     *
     * @required
     * @maps id_campanha_promocional
     */
    public function setIdCampanhaPromocional(int $idCampanhaPromocional): void
    {
        $this->idCampanhaPromocional = $idCampanhaPromocional;
    }

    /**
     * Converts the DeletarPrecoRequest object to a human-readable string representation.
     *
     * @return string The string representation of the DeletarPrecoRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'DeletarPrecoRequest',
            ['idCampanhaPromocional' => $this->idCampanhaPromocional]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['id_campanha_promocional'] = $this->idCampanhaPromocional;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
