<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models;

use ApiB4CLib\ApiHelper;
use stdClass;

class Dimensoes implements \JsonSerializable
{
    /**
     * @var string
     */
    private $altura;

    /**
     * @var string
     */
    private $largura;

    /**
     * @var string
     */
    private $comprimento;

    /**
     * @var string
     */
    private $peso;

    /**
     * @param string $altura
     * @param string $largura
     * @param string $comprimento
     * @param string $peso
     */
    public function __construct(string $altura, string $largura, string $comprimento, string $peso)
    {
        $this->altura = $altura;
        $this->largura = $largura;
        $this->comprimento = $comprimento;
        $this->peso = $peso;
    }

    /**
     * Returns Altura.
     */
    public function getAltura(): string
    {
        return $this->altura;
    }

    /**
     * Sets Altura.
     *
     * @required
     * @maps altura
     */
    public function setAltura(string $altura): void
    {
        $this->altura = $altura;
    }

    /**
     * Returns Largura.
     */
    public function getLargura(): string
    {
        return $this->largura;
    }

    /**
     * Sets Largura.
     *
     * @required
     * @maps largura
     */
    public function setLargura(string $largura): void
    {
        $this->largura = $largura;
    }

    /**
     * Returns Comprimento.
     */
    public function getComprimento(): string
    {
        return $this->comprimento;
    }

    /**
     * Sets Comprimento.
     *
     * @required
     * @maps comprimento
     */
    public function setComprimento(string $comprimento): void
    {
        $this->comprimento = $comprimento;
    }

    /**
     * Returns Peso.
     */
    public function getPeso(): string
    {
        return $this->peso;
    }

    /**
     * Sets Peso.
     *
     * @required
     * @maps peso
     */
    public function setPeso(string $peso): void
    {
        $this->peso = $peso;
    }

    /**
     * Converts the Dimensoes object to a human-readable string representation.
     *
     * @return string The string representation of the Dimensoes object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Dimensoes',
            [
                'altura' => $this->altura,
                'largura' => $this->largura,
                'comprimento' => $this->comprimento,
                'peso' => $this->peso
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['altura']      = $this->altura;
        $json['largura']     = $this->largura;
        $json['comprimento'] = $this->comprimento;
        $json['peso']        = $this->peso;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
