<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models;

use ApiB4CLib\ApiHelper;
use stdClass;

class EstoquesRetira implements \JsonSerializable
{
    /**
     * @var string
     */
    private $filialErp;

    /**
     * @var string
     */
    private $quantidade;

    /**
     * @var string
     */
    private $considerarEstoque;

    /**
     * @var string
     */
    private $loteId;

    /**
     * @param string $filialErp
     * @param string $quantidade
     * @param string $considerarEstoque
     * @param string $loteId
     */
    public function __construct(string $filialErp, string $quantidade, string $considerarEstoque, string $loteId)
    {
        $this->filialErp = $filialErp;
        $this->quantidade = $quantidade;
        $this->considerarEstoque = $considerarEstoque;
        $this->loteId = $loteId;
    }

    /**
     * Returns Filial Erp.
     */
    public function getFilialErp(): string
    {
        return $this->filialErp;
    }

    /**
     * Sets Filial Erp.
     *
     * @required
     * @maps filial_erp
     */
    public function setFilialErp(string $filialErp): void
    {
        $this->filialErp = $filialErp;
    }

    /**
     * Returns Quantidade.
     */
    public function getQuantidade(): string
    {
        return $this->quantidade;
    }

    /**
     * Sets Quantidade.
     *
     * @required
     * @maps quantidade
     */
    public function setQuantidade(string $quantidade): void
    {
        $this->quantidade = $quantidade;
    }

    /**
     * Returns Considerar Estoque.
     */
    public function getConsiderarEstoque(): string
    {
        return $this->considerarEstoque;
    }

    /**
     * Sets Considerar Estoque.
     *
     * @required
     * @maps considerar_estoque
     */
    public function setConsiderarEstoque(string $considerarEstoque): void
    {
        $this->considerarEstoque = $considerarEstoque;
    }

    /**
     * Returns Lote Id.
     */
    public function getLoteId(): string
    {
        return $this->loteId;
    }

    /**
     * Sets Lote Id.
     *
     * @required
     * @maps lote_id
     */
    public function setLoteId(string $loteId): void
    {
        $this->loteId = $loteId;
    }

    /**
     * Converts the EstoquesRetira object to a human-readable string representation.
     *
     * @return string The string representation of the EstoquesRetira object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'EstoquesRetira',
            [
                'filialErp' => $this->filialErp,
                'quantidade' => $this->quantidade,
                'considerarEstoque' => $this->considerarEstoque,
                'loteId' => $this->loteId
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['filial_erp']         = $this->filialErp;
        $json['quantidade']         = $this->quantidade;
        $json['considerar_estoque'] = $this->considerarEstoque;
        $json['lote_id']            = $this->loteId;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
