<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models;

use ApiB4CLib\ApiHelper;
use stdClass;

class ListaDosNivei implements \JsonSerializable
{
    /**
     * @var string
     */
    private $nivel;

    /**
     * @var string
     */
    private $nome;

    /**
     * @var string
     */
    private $permissoes;

    /**
     * @param string $nivel
     * @param string $nome
     * @param string $permissoes
     */
    public function __construct(string $nivel, string $nome, string $permissoes)
    {
        $this->nivel = $nivel;
        $this->nome = $nome;
        $this->permissoes = $permissoes;
    }

    /**
     * Returns Nivel.
     */
    public function getNivel(): string
    {
        return $this->nivel;
    }

    /**
     * Sets Nivel.
     *
     * @required
     * @maps nivel
     */
    public function setNivel(string $nivel): void
    {
        $this->nivel = $nivel;
    }

    /**
     * Returns Nome.
     */
    public function getNome(): string
    {
        return $this->nome;
    }

    /**
     * Sets Nome.
     *
     * @required
     * @maps nome
     */
    public function setNome(string $nome): void
    {
        $this->nome = $nome;
    }

    /**
     * Returns Permissoes.
     */
    public function getPermissoes(): string
    {
        return $this->permissoes;
    }

    /**
     * Sets Permissoes.
     *
     * @required
     * @maps permissoes
     */
    public function setPermissoes(string $permissoes): void
    {
        $this->permissoes = $permissoes;
    }

    /**
     * Converts the ListaDosNivei object to a human-readable string representation.
     *
     * @return string The string representation of the ListaDosNivei object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ListaDosNivei',
            ['nivel' => $this->nivel, 'nome' => $this->nome, 'permissoes' => $this->permissoes]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['nivel']      = $this->nivel;
        $json['nome']       = $this->nome;
        $json['permissoes'] = $this->permissoes;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
