<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models;

use ApiB4CLib\ApiHelper;
use stdClass;

class NewRequestRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $codigo;

    /**
     * @param string $codigo
     */
    public function __construct(string $codigo)
    {
        $this->codigo = $codigo;
    }

    /**
     * Returns Codigo.
     */
    public function getCodigo(): string
    {
        return $this->codigo;
    }

    /**
     * Sets Codigo.
     *
     * @required
     * @maps codigo
     */
    public function setCodigo(string $codigo): void
    {
        $this->codigo = $codigo;
    }

    /**
     * Converts the NewRequestRequest object to a human-readable string representation.
     *
     * @return string The string representation of the NewRequestRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('NewRequestRequest', ['codigo' => $this->codigo]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['codigo'] = $this->codigo;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
