<?php

declare(strict_types=1);

/*
 * ApiB4CLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApiB4CLib\Models;

use ApiB4CLib\ApiHelper;
use stdClass;

class Personalizaco implements \JsonSerializable
{
    /**
     * @var string
     */
    private $sku;

    /**
     * @var int
     */
    private $nivel;

    /**
     * @var int
     */
    private $tipo;

    /**
     * @var int
     */
    private $arteFinalista;

    /**
     * @param string $sku
     * @param int $nivel
     * @param int $tipo
     * @param int $arteFinalista
     */
    public function __construct(string $sku, int $nivel, int $tipo, int $arteFinalista)
    {
        $this->sku = $sku;
        $this->nivel = $nivel;
        $this->tipo = $tipo;
        $this->arteFinalista = $arteFinalista;
    }

    /**
     * Returns Sku.
     */
    public function getSku(): string
    {
        return $this->sku;
    }

    /**
     * Sets Sku.
     *
     * @required
     * @maps sku
     */
    public function setSku(string $sku): void
    {
        $this->sku = $sku;
    }

    /**
     * Returns Nivel.
     */
    public function getNivel(): int
    {
        return $this->nivel;
    }

    /**
     * Sets Nivel.
     *
     * @required
     * @maps nivel
     */
    public function setNivel(int $nivel): void
    {
        $this->nivel = $nivel;
    }

    /**
     * Returns Tipo.
     */
    public function getTipo(): int
    {
        return $this->tipo;
    }

    /**
     * Sets Tipo.
     *
     * @required
     * @maps tipo
     */
    public function setTipo(int $tipo): void
    {
        $this->tipo = $tipo;
    }

    /**
     * Returns Arte Finalista.
     */
    public function getArteFinalista(): int
    {
        return $this->arteFinalista;
    }

    /**
     * Sets Arte Finalista.
     *
     * @required
     * @maps arte_finalista
     */
    public function setArteFinalista(int $arteFinalista): void
    {
        $this->arteFinalista = $arteFinalista;
    }

    /**
     * Converts the Personalizaco object to a human-readable string representation.
     *
     * @return string The string representation of the Personalizaco object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Personalizaco',
            [
                'sku' => $this->sku,
                'nivel' => $this->nivel,
                'tipo' => $this->tipo,
                'arteFinalista' => $this->arteFinalista
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['sku']            = $this->sku;
        $json['nivel']          = $this->nivel;
        $json['tipo']           = $this->tipo;
        $json['arte_finalista'] = $this->arteFinalista;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
